// Main source file for the OpenTuna UMCS Installer.
// This program handles the user interface, installation logic for OpenTuna
// (a Memory Card exploit), and interacts with various PS2 system services
// for file I/O, graphics display, and controller input.

//#define __DEBUG_PRINTF__
#ifdef __DEBUG_PRINTF__
#define PRINTF(arg...) printf(arg...)
#else
#define PRINTF(arg...)
#endif
/*------------------------------------------------------------*/
#include "main.h"
// BMP headers for UI graphics
#include "BMP/complete.h"
#include "BMP/error.h"
#include "BMP/wait.h"
#include "BMP/MensajeA.h" // Error message A bitmap
#include "BMP/MensajeB.h" // Error message B bitmap
#include "BMP/MensajeC.h" // Error message C bitmap
#include "BMP/MensajeD.h" // Error message D bitmap
#include "BMP/MensajeE.h" // Error message E bitmap
#include "BMP/MensajeF.h" // Error message F bitmap
#include "BMP/NON_COMPATIBLE.h" // Non-compatible ROM message bitmap
#include "BMP/INST_SLOT_1.h"    // Memory card slot 1 selection screen bitmap
#include "BMP/INST_SLOT_2.h"    // Memory card slot 2 selection screen bitmap

// Enum defining different PS2 console types based on ROM version for icon compatibility.
enum ICN
{
	SLIMS = 0,	  // Slim consoles (ROMVER >= 0x190) and SCPH-5000X with ROMVER 0x190
	FATS,		  // Fat consoles (0x110, 0x120, 0x150, 0x160) excluding 0x170
	FAT170,		  // Specific Fat console model (ROMVER 0x170)
	PROTOKERNELS, // Early prototype kernel ROMs (0x100, 0x101). Defined but not used for icon generation by this installer.
	UNSUPPORTED,  // Any other ROM version not covered above.
};

// Aliases for icon types, used in manifest files.
char* ICONTYPE_ALIAS[4] = {"190+","110+","170 ","100 "};
// Filenames for different icon variants.
char* ICONFILE_NAMES[4] = {"slims","fats","fat170","protok"};

// Enum defining the different states of the installer application.
enum STATE
{
	STATE_MC0,			// Main screen: Memory Card slot 0 selected for installation.
	STATE_MC1,			// Main screen: Memory Card slot 1 selected for installation.
	STATE_INSTALL,		// Installation in progress.
	STATE_FINISH,		// Installation completed successfully.
	STATE_ERROR,		// Error occurred during installation.
	STATE_BROWSER,		// Exiting to PS2 Browser.
	STATE_UNSUPPORTED,	// Console's ROM version is not supported.
};

// Determines the icon type category based on the console's ROMVERSION.
// This helps in selecting the appropriate OpenTuna icon variant for the specific console model.
int GetIconType(unsigned long int ROMVERSION)
{
	int icontype;

	if (ROMVERSION >= 0x190) {
		icontype = SLIMS;
	} else if (ROMVERSION == 0x170) { // Specific check for 0x170 first
		icontype = FAT170;
	} else if (ROMVERSION >= 0x110 && ROMVERSION < 0x190) { // General FATS range
		icontype = FATS;
	} else {
		// This includes PROTOKERNELS (0x100, 0x101) and any other unspecified versions.
		// PROTOKERNELS are intentionally mapped to UNSUPPORTED as per the enum ICN comment.
		icontype = UNSUPPORTED;
	}

	return icontype;
}

// External declarations for embedded binary file data and their sizes.
// These are generated by bin2s or bin2c and linked into the executable.
// Each pair consists of a byte array for the file data and an integer for its size.
//----------------------------------------//
// INSTALL/BOOT/ directory files
extern u8 BOOT_BOOT_ELF[];
extern int size_BOOT_BOOT_ELF;
extern u8 BOOT_BOOT_ICN[];
extern int size_BOOT_BOOT_ICN;
extern u8 BOOT_BOOT2_ELF[];
extern int size_BOOT_BOOT2_ELF;
extern u8 BOOT_CONFIG_INI[];
extern int size_BOOT_CONFIG_INI;
extern u8 BOOT_COPY_ICN[];
extern int size_BOOT_COPY_ICN;
extern u8 BOOT_DEL_ICN[];
extern int size_BOOT_DEL_ICN;
extern u8 BOOT_ESR_ELF[];
extern int size_BOOT_ESR_ELF;
extern u8 BOOT_ICON_SYS[];
extern int size_BOOT_ICON_SYS;
//----------------------------------------//
// INSTALL/FMCBD-1.953/ directory files
extern u8 FMCBD_1_953_COPY_ICN[];
extern int size_FMCBD_1_953_COPY_ICN;
extern u8 FMCBD_1_953_DEL_ICN[];
extern int size_FMCBD_1_953_DEL_ICN;
extern u8 FMCBD_1_953_FMCB_ICN[];
extern int size_FMCBD_1_953_FMCB_ICN;
extern u8 FMCBD_1_953_FMCBD_1_953_ELF[];
extern int size_FMCBD_1_953_FMCBD_1_953_ELF;
extern u8 FMCBD_1_953_ICON_SYS[];
extern int size_FMCBD_1_953_ICON_SYS;
//----------------------------------------//
// INSTALL/FMCBD-1.966/ directory files
extern u8 FMCBD_1_966_COPY_ICN[];
extern int size_FMCBD_1_966_COPY_ICN;
extern u8 FMCBD_1_966_DEL_ICN[];
extern int size_FMCBD_1_966_DEL_ICN;
extern u8 FMCBD_1_966_FMCB_ICN[];
extern int size_FMCBD_1_966_FMCB_ICN;
extern u8 FMCBD_1_966_FMCBD_1_966_ELF[];
extern int size_FMCBD_1_966_FMCBD_1_966_ELF;
extern u8 FMCBD_1_966_ICON_SYS[];
extern int size_FMCBD_1_966_ICON_SYS;
//----------------------------------------//
// INSTALL/OPENTUNA/ directory files (specific OpenTuna exploit icons)
extern u8 opentuna_sys[]; // General icon.sys for OpenTuna folder, matches bin2s symbol name
extern int size_opentuna_sys; // Size of opentuna_sys data
extern u8 opentuna_slims[]; // Icon for Slim PS2 models
extern int size_opentuna_slims;
extern u8 opentuna_fats[];  // Icon for common Fat PS2 models
extern int size_opentuna_fats;
extern u8 opentuna_fat170[]; // Icon for ROMVER 0x170 Fat PS2 models
extern int size_opentuna_fat170;
//----------------------------------------//
// INSTALL/OSDMENU/ directory files
extern u8 OSDMENU_COPY_ICN[];
extern int size_OSDMENU_COPY_ICN;
extern u8 OSDMENU_DEL_ICN[];
extern int size_OSDMENU_DEL_ICN;
extern u8 OSDMENU_ICON_SYS[];
extern int size_OSDMENU_ICON_SYS;
extern u8 OSDMENU_LAUNCHER_ELF[];
extern int size_OSDMENU_LAUNCHER_ELF;
extern u8 OSDMENU_LIST_ICN[];
extern int size_OSDMENU_LIST_ICN;
extern u8 OSDMENU_OSDMENU_CNF[];
extern int size_OSDMENU_OSDMENU_CNF;
extern u8 OSDMENU_OSDMENU_ELF[];
extern int size_OSDMENU_OSDMENU_ELF;
extern u8 OSDMENU_PATCHER_ELF[];
extern int size_OSDMENU_PATCHER_ELF;
//----------------------------------------//
// INSTALL/POPSTARTER/ directory files
extern u8 POPSTARTER_DEL_ICN[];
extern int size_POPSTARTER_DEL_ICN;
extern u8 POPSTARTER_ICON_SYS[];
extern int size_POPSTARTER_ICON_SYS;
extern u8 POPSTARTER_IPCONFIG_DAT[];
extern int size_POPSTARTER_IPCONFIG_DAT;
extern u8 POPSTARTER_LIST_ICN[];
extern int size_POPSTARTER_LIST_ICN;
extern u8 POPSTARTER_POWEROFF_IRX[];
extern int size_POPSTARTER_POWEROFF_IRX;
extern u8 POPSTARTER_PS2DEV9_IRX[];
extern int size_POPSTARTER_PS2DEV9_IRX;
extern u8 POPSTARTER_PS2IP_IRX[];
extern int size_POPSTARTER_PS2IP_IRX;
extern u8 POPSTARTER_PS2SMAP_IRX[];
extern int size_POPSTARTER_PS2SMAP_IRX;
extern u8 POPSTARTER_SMBCONFIG_DAT[];
extern int size_POPSTARTER_SMBCONFIG_DAT;
extern u8 POPSTARTER_SMBMAN_IRX[];
extern int size_POPSTARTER_SMBMAN_IRX;
extern u8 POPSTARTER_SMSUTILS_IRX[];
extern int size_POPSTARTER_SMSUTILS_IRX;
extern u8 POPSTARTER_USBD_IRX[];
extern int size_POPSTARTER_USBD_IRX;
extern u8 POPSTARTER_USBHDFSD_IRX[];
extern int size_POPSTARTER_USBHDFSD_IRX;
//----------------------------------------//
// INSTALL/POWEROFF/ directory files
extern u8 POWEROFF_DEL_ICN[];
extern int size_POWEROFF_DEL_ICN;
extern u8 POWEROFF_ICON_SYS[];
extern int size_POWEROFF_ICON_SYS;
extern u8 POWEROFF_LIST_ICN[];
extern int size_POWEROFF_LIST_ICN;
extern u8 POWEROFF_POWEROFF_ELF[];
extern int size_POWEROFF_POWEROFF_ELF;
//----------------------------------------//
// INSTALL/PS1_DKWDRV/ directory files
extern u8 PS1_DKWDRV_COPY_ICN[];
extern int size_PS1_DKWDRV_COPY_ICN;
extern u8 PS1_DKWDRV_DEL_ICN[];
extern int size_PS1_DKWDRV_DEL_ICN;
extern u8 PS1_DKWDRV_DKWDRV_ELF[];
extern int size_PS1_DKWDRV_DKWDRV_ELF;
extern u8 PS1_DKWDRV_ICON_SYS[];
extern int size_PS1_DKWDRV_ICON_SYS;
extern u8 PS1_DKWDRV_LIST_ICN[];
extern int size_PS1_DKWDRV_LIST_ICN;
extern u8 PS1_DKWDRV_TITLE_CFG[];
extern int size_PS1_DKWDRV_TITLE_CFG;
//----------------------------------------//
// INSTALL/SYS-CONF/ directory files
extern u8 SYS_CONF_COPY_ICN[];
extern int size_SYS_CONF_COPY_ICN;
extern u8 SYS_CONF_DEL_ICN[];
extern int size_SYS_CONF_DEL_ICN;
extern u8 SYS_CONF_ENDVDPL_IRX[];
extern int size_SYS_CONF_ENDVDPL_IRX;
extern u8 SYS_CONF_FREEMCB_CNF[];
extern int size_SYS_CONF_FREEMCB_CNF;
extern u8 SYS_CONF_ICON_SYS[];
extern int size_SYS_CONF_ICON_SYS;
extern u8 SYS_CONF_IPCONFIG_DAT[];
extern int size_SYS_CONF_IPCONFIG_DAT;
extern u8 SYS_CONF_LAUNCHELF_CNF[];
extern int size_SYS_CONF_LAUNCHELF_CNF;
extern u8 SYS_CONF_PS2BBL_INI[];
extern int size_SYS_CONF_PS2BBL_INI;
extern u8 SYS_CONF_PSXBBL_INI[];
extern int size_SYS_CONF_PSXBBL_INI;
extern u8 SYS_CONF_SYSCONF_ICN[];
extern int size_SYS_CONF_SYSCONF_ICN;
extern u8 SYS_CONF_USBD_IRX[];
extern int size_SYS_CONF_USBD_IRX;
extern u8 SYS_CONF_USBHDFSD_IRX[];
extern int size_SYS_CONF_USBHDFSD_IRX;
//----------------------------------------//
// INSTALL/SYS_FMCB-CFG/ directory files
extern u8 SYS_FMCB_CFG_COPY_ICN[];
extern int size_SYS_FMCB_CFG_COPY_ICN;
extern u8 SYS_FMCB_CFG_DEL_ICN[];
extern int size_SYS_FMCB_CFG_DEL_ICN;
extern u8 SYS_FMCB_CFG_FMCB_CFG_ELF[];
extern int size_SYS_FMCB_CFG_FMCB_CFG_ELF;
extern u8 SYS_FMCB_CFG_ICON_SYS[];
extern int size_SYS_FMCB_CFG_ICON_SYS;
extern u8 SYS_FMCB_CFG_LIST_ICN[];
extern int size_SYS_FMCB_CFG_LIST_ICN;
extern u8 SYS_FMCB_CFG_TITLE_CFG[];
extern int size_SYS_FMCB_CFG_TITLE_CFG;
//----------------------------------------//

// Embedded IOP (Input/Output Processor) driver modules.
// These are typically included from the PS2SDK.
extern unsigned char SIO2MAN_irx[]; // SIO2 (Serial I/O) Manager
extern unsigned int size_SIO2MAN_irx;
extern unsigned char PADMAN_irx[];  // PAD (Controller) Manager
extern unsigned int size_PADMAN_irx;
extern unsigned char MCMAN_irx[];   // Memory Card Manager
extern unsigned int size_MCMAN_irx;
extern unsigned char MCSERV_irx[];  // Memory Card Server
extern unsigned int size_MCSERV_irx;

// Flag to indicate if the PAD system has been initialized.
static int pad_inited = 0;

//--------------------------------------------------------------
// Checks if a file exists at the given filepath.
// Args:
//   filepath: The full path to the file (e.g., "mc0:/BOOT/BOOT.ELF").
// Returns:
//   1 if the file exists.
//   0 if the file does not exist or an error occurred.
static int file_exists(char *filepath)
{
	int fdn; // File descriptor

	// Try to open the file in read-only mode.
	fdn = open(filepath, O_RDONLY);
	if (fdn < 0) // If open fails (negative fdn), file likely doesn't exist or is inaccessible.
		return 0;

	// File opened successfully, so it exists. Close it.
	close(fdn);
	return 1;
}

//--------------------------------------------------------------
// Resets the IOP (Input/Output Processor) and re-initializes RPC (Remote Procedure Call).
// This is a standard procedure to ensure a clean state for IOP modules.
static void Reset_IOP(void)
{
	//parrado (Original comment attributing this specific sequence)
	SifInitRpc(0); // Initialize SIF RPC.
	while (!SifIopReset("", 0)) // Reset IOP. Loop until successful.
	{
	};
	while (!SifIopSync()) // Synchronize with IOP. Loop until successful.
	{
	};
	SifInitRpc(0); // Re-initialize SIF RPC after reset.
}

//=============================================================
// Displays a BMP image (32-bit RGBA) centered on the screen.
// Args:
//   W: Width of the BMP image.
//   H: Height of the BMP image.
//   data: Pointer to the raw BMP pixel data.
static void display_bmp(u16 W, u16 H, u32 *data)
{
	gs_print_bitmap(
		(gs_get_max_x() - W) / 2, // Center X coordinate
		(gs_get_max_y() - H) / 2, // Center Y coordinate
		W,						  // Image width
		H,						  // Image height
		data					  // Pointer to image data
	);
	PRINTF("array displayed\n"); // Debug print
}

//=============================================================
// Recursively deletes a folder and its contents.
// This function was obtained from SP193's FreeMcBoot installer.
// Args:
//   folder: The full path to the folder to be deleted (e.g., "mc0:/OPENTUNA").
// Returns:
//   0 on success.
//  -1 or other non-zero value on failure (e.g., if a file/folder couldn't be deleted).
static int DeleteFolder(const char *folder)
{
	DIR *d = opendir(folder);
	size_t path_len = strlen(folder);
	int r = -1;

	if (d)
	{
		//scr_printf("Detected [%s], deleting...\n",folder);
		struct dirent *p;

		r = 0;
		while (!r && (p = readdir(d)))
		{
			int r2 = -1;
			char *buf;
			size_t len;

			/* Skip the names "." and ".." as we don't want to recurse on them. */
			if (!strcmp(p->d_name, ".") || !strcmp(p->d_name, ".."))
				continue;

			len = path_len + strlen(p->d_name) + 2;
			buf = malloc(len);

			if (buf == NULL) {
				PRINTF("DeleteFolder: malloc failed for path component in %s for %s\n", folder, p->d_name);
				// r2 is already -1, which will be propagated to r, indicating an error.
			} else {
				struct stat statbuf;
				snprintf(buf, len, "%s/%s", folder, p->d_name);
				if (!stat(buf, &statbuf)) { // stat succeeded
					if (S_ISDIR(statbuf.st_mode)) {
						r2 = DeleteFolder(buf);
					} else {
						r2 = unlink(buf);
					}
				} else { // stat failed
					PRINTF("DeleteFolder: stat failed for %s. errno: %d\n", buf, errno);
					// r2 is already -1 (initialized at the start of the loop iteration), error will be propagated.
				}
				free(buf);
			}
			r = r2;
		}
		closedir(d);
	}

	if (!r)
		r = rmdir(folder);

	return r;
}

//=============================================================
// Initializes core PS2 systems and loads necessary IOP modules.
// This sets up the environment for the installer to function.
static void InitPS2(void)
{
	Reset_IOP(); // Reset IOP and basic system services.
	SifInitIopHeap(); // Initialize IOP heap for module allocation.
	SifLoadFileInit(); // Initialize SIF services for loading files (modules) to IOP.
	fioInit(); // Initialize File I/O library for EE (Emotion Engine).

	// Apply SBV (Sony Bridge Verifier) patches to enable loading IRX modules
	// from EE memory and to disable prefix checks for paths.
	sbv_patch_enable_lmb(); // Load Module Buffer: Allows loading IRX from memory.
	sbv_patch_disable_prefix_check(); // Disables path prefix checking (e.g. "mc0:/").

	// Load essential IOP modules from embedded data.
	// These modules provide services for SIO2 (controllers, memory cards), PAD, and MC.
	SifExecModuleBuffer(SIO2MAN_irx, size_SIO2MAN_irx, 0, NULL, NULL); // Serial I/O manager
	SifExecModuleBuffer(PADMAN_irx, size_PADMAN_irx, 0, NULL, NULL);  // Pad controller manager
	SifExecModuleBuffer(MCMAN_irx, size_MCMAN_irx, 0, NULL, NULL);    // Memory card manager (low-level)
	SifExecModuleBuffer(MCSERV_irx, size_MCSERV_irx, 0, NULL, NULL);  // Memory card server (high-level)
    sbv_patch_fileio(); // Apply file I/O patches (e.g., for wider compatibility). THANKS fjtrujy

	mcInit(MC_TYPE_MC); // Initialize memory card driver with standard type (MC_TYPE_MC) for potentially broader compatibility.
	PadInitPads(); // Initialize the pad (controller) input system.
}

// Writes an embedded file (from memory) to the specified path on a memory card.
// It only writes the file if it does not already exist at the target location.
// Args:
//   embed_file: Pointer to the embedded file data in memory.
//   embed_size: Size of the embedded file data in bytes.
//   folder:     Target folder name on the memory card (e.g., "OPENTUNA").
//   filename:   Target filename on the memory card (e.g., "icon.icn").
//   mcport:     Memory card port number (0 for mc0:, 1 for mc1:).
// Returns:
//    0: Success (file written or already exists).
//   -1: Failed to open the target file for writing.
//   -2: Failed to write the complete file data.
//   -3: snprintf failed to construct the target path (should not happen with valid inputs).
//   -4: Constructed target path was truncated (MAX_PATH too small for the generated path).
static int write_embed(void *embed_file, const int embed_size, char *folder, char *filename, int mcport)
{
	char target[MAX_PATH];
	int path_len;

	path_len = snprintf(target, MAX_PATH, "mc%d:/%s/%s", mcport, folder, filename);

	if (path_len < 0) {
		// snprintf failed (encoding error or other system issue)
		PRINTF("write_embed: snprintf failed to construct path for mc%d:/%s/%s. Error: %d\n", mcport, folder, filename, path_len);
		return -3; // Path construction failure
	} else if (path_len >= MAX_PATH) {
		// Path was truncated
		PRINTF("write_embed: path truncated for mc%d:/%s/%s. Required: %d, Available: %d\n", mcport, folder, filename, path_len, MAX_PATH);
		return -4; // Path truncation
	}

	if (open(target, O_RDONLY) < 0) //if not exist
	{
		int ret, fd;
		if ((fd = open(target, O_CREAT | O_WRONLY | O_TRUNC)) < 0)
		{
			return -1;
		}
		ret = write(fd, embed_file, embed_size);
		if (ret != embed_size)
		{
			return -2;
		}
		close(fd);
	}

	PRINTF("embed file written: %s\n", target);
	return 0;
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Performs the installation of OpenTuna and associated files to the selected memory card.
// Args:
//   mcport:       The memory card slot to install to (0 for mc0, 1 for mc1).
//   icon_variant: The specific icon variant (SLIMS, FATS, etc.) to install,
//                 determined by the console's ROM version.
// Returns:
//   0 on successful installation.
//   Non-zero error code on failure:
//     1: mcGetInfo failed (no MC or other MC error).
//     2: Memory card is not a PS2 Memory Card.
//     3: Not enough free space on the Memory Card.
//     4: Pre-existing OpenTuna files found (installation aborted to prevent overwrite issues).
//     6: Generic file write/open error during installation of core files or manifest.
//     7: DeleteFolder failed for one of the target directories.
//     8: mcMkDir failed to create a directory.
//    (write_embed can also return -1, -2, -3, -4 which are handled as error 6 by caller)
static int install(int mcport, int icon_variant)
{
	char version_manifest_path[MAX_PATH];
    char temp_path[MAX_PATH];
	int ret, retorno,fd;
	static int mc_Type, mc_Free, mc_Format;
	
	// Construct version_manifest_path safely
    snprintf(version_manifest_path, MAX_PATH, "mc%d:/OPENTUNA/icon_%s.cnf", mcport, ICONFILE_NAMES[icon_variant]);
    // It's good practice to check snprintf result, but given the fixed components, it's unlikely to fail/truncate here.
    // For extreme robustness, a check could be added. For now, assume it's fine for this specific path.

	mcGetInfo(mcport, 0, &mc_Type, &mc_Free, &mc_Format);
	mcSync(0, NULL, &ret); // 'ret' will contain the result of the mcGetInfo operation
	PRINTF("mc_Type: %d, mc_Free: %d, mc_Format: %d, mcGetInfo_ret: %d\n", mc_Type, mc_Free, mc_Format, ret); // Enhanced PRINTF

	// Check if mcGetInfo failed (0 means success for mcSync result from mc commands)
	if (ret != 0)
	{
		PRINTF("Install: mcGetInfo failed or reported an error. mcSync ret: %d\n", ret);
		return 1; // Return error code 1 (generalized MC error)
	}

	//If it is not a PS2 MC, we have an error:
	if (mc_Type != sceMcTypePS2)
	{
		return 2;
	}

	//If there's no free space, we have an error:
	if (mc_Free < 20)
	{
		return 3;
	}
   snprintf(temp_path, MAX_PATH, "mc%u:BOOT", mcport);
	   if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
   snprintf(temp_path, MAX_PATH, "mc%u:LDR_FMCBD-1.966", mcport);
	   if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
   snprintf(temp_path, MAX_PATH, "mc%u:SYS_FMCBCFG", mcport);
	   if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
   snprintf(temp_path, MAX_PATH, "mc%u:SYS_FMCB-CFG", mcport);
	   if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
    snprintf(temp_path, MAX_PATH, "mc%u:FORTUNA", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
	snprintf(temp_path, MAX_PATH, "mc%u:OPENTUNA", mcport); // This one is repeated later, ensure it's intended.
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
    snprintf(temp_path, MAX_PATH, "mc%u:SYS-CONF", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:FUNTUNA-FORK", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:BXEXEC-FUNTUNA", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:FUNTUNA", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:BXEXEC-OPENTUNA", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:FMCBD-1.953", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:FMCBD-1.966", mcport); // This one is repeated (LDR_FMCBD-1.966 vs FMCBD-1.966) - seems okay.
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:OPENTUNA", mcport); // Repeated
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:OSDMENU", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:POPSTARTER", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:POWEROFF", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
snprintf(temp_path, MAX_PATH, "mc%u:PS1_DKWDRV", mcport);
		if (DeleteFolder(temp_path) != 0) { PRINTF("Install: Failed to delete folder %s\n", temp_path); return 7; }
    
	//If the files exists, we have an error:
	if (mcport == 0)
	{
		if (file_exists("mc0:/OPENTUNA/icon.icn"))
		{
			return 4;
		}
		if (file_exists("mc0:/OPENTUNA/icon.sys"))
		{
			return 4;
		}
	}
	else
	{
		if (file_exists("mc1:/OPENTUNA/icon.icn"))
		{
			return 4;
		}
		if (file_exists("mc1:/OPENTUNA/icon.sys"))
		{
			return 4;
		}
	}

	// Creating directories
	ret = mcMkDir(mcport, 0, "OPENTUNA");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for OPENTUNA, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret); // Existing mcSync, ret is overwritten here.
	// If mcSync itself needs to be checked for a specific error: int ret_sync; mcSync(0, NULL, &ret_sync); if(ret_sync...)

	ret = mcMkDir(mcport, 0, "BOOT");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for BOOT, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret);

	ret = mcMkDir(mcport, 0, "FMCBD-1.953");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for FMCBD-1.953, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret);

	ret = mcMkDir(mcport, 0, "FMCBD-1.966");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for FMCBD-1.966, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret);

	ret = mcMkDir(mcport, 0, "OSDMENU");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for OSDMENU, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret);

	ret = mcMkDir(mcport, 0, "POPSTARTER");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for POPSTARTER, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret);

	ret = mcMkDir(mcport, 0, "POWEROFF");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for POWEROFF, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret);

	ret = mcMkDir(mcport, 0, "PS1_DKWDRV");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for PS1_DKWDRV, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret);

	ret = mcMkDir(mcport, 0, "SYS-CONF");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for SYS-CONF, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret);

	ret = mcMkDir(mcport, 0, "SYS_FMCB-CFG");
	if (ret != 0) { PRINTF("Install: mcMkDir failed for SYS_FMCB-CFG, error: %d\n", ret); return 8; }
	mcSync(0, NULL, &ret);

	retorno = -12; ///to ensure installation quits if none of the hacked icons are written
	if (icon_variant == SLIMS)
	{
		retorno = write_embed(&opentuna_slims, size_opentuna_slims, "OPENTUNA", "icon.icn", mcport);
	}
	else if (icon_variant == FATS)
	{
		retorno = write_embed(&opentuna_fats, size_opentuna_fats, "OPENTUNA", "icon.icn", mcport);
	}
	else if (icon_variant == FAT170)
	{
		retorno = write_embed(&opentuna_fat170, size_opentuna_fat170, "OPENTUNA", "icon.icn", mcport);
	}
	if (retorno < 0)
	{
		return 6;
	}
	// <FILES SHARED BY ALL ICONS FROM NOW ON>
	retorno = write_embed(&opentuna_sys, size_opentuna_sys, "OPENTUNA", "icon.sys", mcport);
	if (retorno < 0)
	{
		return 6;
	}
	if ((fd = open(version_manifest_path, O_CREAT | O_WRONLY | O_TRUNC)) >= 0) {
		ret = write(fd, ICONTYPE_ALIAS[icon_variant], 4); // This will allow identifying the hacked icon variant without risking your mc contents
		if (ret != 4) {
			PRINTF("Install: Failed to write version manifest %s. Expected 4 bytes, wrote %d\n", version_manifest_path, ret);
			close(fd);
			return 6; // File write error
		}
		close(fd);
	} else {
		PRINTF("Install: Failed to open/create version manifest %s, error code: %d\n", version_manifest_path, fd);
		return 6; // File open error
	}

	// Writing files for BOOT directory...
    retorno = write_embed(&BOOT_BOOT_ELF, size_BOOT_BOOT_ELF, "BOOT", "BOOT.ELF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&BOOT_BOOT_ICN, size_BOOT_BOOT_ICN, "BOOT", "BOOT.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&BOOT_BOOT2_ELF, size_BOOT_BOOT2_ELF, "BOOT", "BOOT2.ELF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&BOOT_CONFIG_INI, size_BOOT_CONFIG_INI, "BOOT", "CONFIG.INI", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&BOOT_COPY_ICN, size_BOOT_COPY_ICN, "BOOT", "copy.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&BOOT_DEL_ICN, size_BOOT_DEL_ICN, "BOOT", "del.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&BOOT_ESR_ELF, size_BOOT_ESR_ELF, "BOOT", "ESR.ELF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&BOOT_ICON_SYS, size_BOOT_ICON_SYS, "BOOT", "icon.sys", mcport);
if (retorno < 0)
{
    return 6;
}

// Writing files for FMCBD-1.953 directory...
retorno = write_embed(&FMCBD_1_953_COPY_ICN, size_FMCBD_1_953_COPY_ICN, "FMCBD-1.953", "copy.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&FMCBD_1_953_DEL_ICN, size_FMCBD_1_953_DEL_ICN, "FMCBD-1.953", "del.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&FMCBD_1_953_FMCB_ICN, size_FMCBD_1_953_FMCB_ICN, "FMCBD-1.953", "FMCB.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&FMCBD_1_953_FMCBD_1_953_ELF, size_FMCBD_1_953_FMCBD_1_953_ELF, "FMCBD-1.953", "FMCBD-1.953.ELF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&FMCBD_1_953_ICON_SYS, size_FMCBD_1_953_ICON_SYS, "FMCBD-1.953", "icon.sys", mcport);
if (retorno < 0)
{
    return 6;
}

// Writing files for FMCBD-1.966 directory...
retorno = write_embed(&FMCBD_1_966_COPY_ICN, size_FMCBD_1_966_COPY_ICN, "FMCBD-1.966", "copy.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&FMCBD_1_966_DEL_ICN, size_FMCBD_1_966_DEL_ICN, "FMCBD-1.966", "del.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&FMCBD_1_966_FMCB_ICN, size_FMCBD_1_966_FMCB_ICN, "FMCBD-1.966", "FMCB.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&FMCBD_1_966_FMCBD_1_966_ELF, size_FMCBD_1_966_FMCBD_1_966_ELF, "FMCBD-1.966", "FMCBD-1.966.ELF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&FMCBD_1_966_ICON_SYS, size_FMCBD_1_966_ICON_SYS, "FMCBD-1.966", "icon.sys", mcport);
if (retorno < 0)
{
    return 6;
}

// Writing files for OSDMENU directory...
retorno = write_embed(&OSDMENU_COPY_ICN, size_OSDMENU_COPY_ICN, "OSDMENU", "copy.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&OSDMENU_DEL_ICN, size_OSDMENU_DEL_ICN, "OSDMENU", "del.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&OSDMENU_ICON_SYS, size_OSDMENU_ICON_SYS, "OSDMENU", "icon.sys", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&OSDMENU_LAUNCHER_ELF, size_OSDMENU_LAUNCHER_ELF, "OSDMENU", "launcher.elf", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&OSDMENU_LIST_ICN, size_OSDMENU_LIST_ICN, "OSDMENU", "list.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&OSDMENU_OSDMENU_CNF, size_OSDMENU_OSDMENU_CNF, "OSDMENU", "OSDMENU.CNF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&OSDMENU_OSDMENU_ELF, size_OSDMENU_OSDMENU_ELF, "OSDMENU", "OSDMENU.ELF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&OSDMENU_PATCHER_ELF, size_OSDMENU_PATCHER_ELF, "OSDMENU", "patcher.elf", mcport);
if (retorno < 0)
{
    return 6;
}

// Writing files for POPSTARTER directory...
retorno = write_embed(&POPSTARTER_DEL_ICN, size_POPSTARTER_DEL_ICN, "POPSTARTER", "del.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_ICON_SYS, size_POPSTARTER_ICON_SYS, "POPSTARTER", "icon.sys", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_IPCONFIG_DAT, size_POPSTARTER_IPCONFIG_DAT, "POPSTARTER", "IPCONFIG.DAT", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_LIST_ICN, size_POPSTARTER_LIST_ICN, "POPSTARTER", "list.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_POWEROFF_IRX, size_POPSTARTER_POWEROFF_IRX, "POPSTARTER", "poweroff.irx", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_PS2DEV9_IRX, size_POPSTARTER_PS2DEV9_IRX, "POPSTARTER", "ps2dev9.irx", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_PS2IP_IRX, size_POPSTARTER_PS2IP_IRX, "POPSTARTER", "ps2ip.irx", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_PS2SMAP_IRX, size_POPSTARTER_PS2SMAP_IRX, "POPSTARTER", "ps2smap.irx", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_SMBCONFIG_DAT, size_POPSTARTER_SMBCONFIG_DAT, "POPSTARTER", "SMBCONFIG.DAT", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_SMBMAN_IRX, size_POPSTARTER_SMBMAN_IRX, "POPSTARTER", "smbman.irx", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_SMSUTILS_IRX, size_POPSTARTER_SMSUTILS_IRX, "POPSTARTER", "SMSUTILS.irx", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_USBD_IRX, size_POPSTARTER_USBD_IRX, "POPSTARTER", "usbd.irx", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POPSTARTER_USBHDFSD_IRX, size_POPSTARTER_USBHDFSD_IRX, "POPSTARTER", "usbhdfsd.irx", mcport);
if (retorno < 0)
{
    return 6;
}

// Writing files for POWEROFF directory...
retorno = write_embed(&POWEROFF_DEL_ICN, size_POWEROFF_DEL_ICN, "POWEROFF", "del.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POWEROFF_ICON_SYS, size_POWEROFF_ICON_SYS, "POWEROFF", "icon.sys", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POWEROFF_LIST_ICN, size_POWEROFF_LIST_ICN, "POWEROFF", "list.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&POWEROFF_POWEROFF_ELF, size_POWEROFF_POWEROFF_ELF, "POWEROFF", "POWEROFF.ELF", mcport);
if (retorno < 0)
{
    return 6;
}

// Writing files for PS1_DKWDRV directory...
retorno = write_embed(&PS1_DKWDRV_COPY_ICN, size_PS1_DKWDRV_COPY_ICN, "PS1_DKWDRV", "copy.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&PS1_DKWDRV_DEL_ICN, size_PS1_DKWDRV_DEL_ICN, "PS1_DKWDRV", "del.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&PS1_DKWDRV_DKWDRV_ELF, size_PS1_DKWDRV_DKWDRV_ELF, "PS1_DKWDRV", "DKWDRV.ELF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&PS1_DKWDRV_ICON_SYS, size_PS1_DKWDRV_ICON_SYS, "PS1_DKWDRV", "icon.sys", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&PS1_DKWDRV_LIST_ICN, size_PS1_DKWDRV_LIST_ICN, "PS1_DKWDRV", "list.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&PS1_DKWDRV_TITLE_CFG, size_PS1_DKWDRV_TITLE_CFG, "PS1_DKWDRV", "title.cfg", mcport);
if (retorno < 0)
{
    return 6;
}

// Writing files for SYS-CONF directory...
retorno = write_embed(&SYS_CONF_COPY_ICN, size_SYS_CONF_COPY_ICN, "SYS-CONF", "copy.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_DEL_ICN, size_SYS_CONF_DEL_ICN, "SYS-CONF", "del.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_ENDVDPL_IRX, size_SYS_CONF_ENDVDPL_IRX, "SYS-CONF", "endvdpl.irx", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_FREEMCB_CNF, size_SYS_CONF_FREEMCB_CNF, "SYS-CONF", "FREEMCB.CNF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_ICON_SYS, size_SYS_CONF_ICON_SYS, "SYS-CONF", "icon.sys", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_IPCONFIG_DAT, size_SYS_CONF_IPCONFIG_DAT, "SYS-CONF", "IPCONFIG.DAT", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_LAUNCHELF_CNF, size_SYS_CONF_LAUNCHELF_CNF, "SYS-CONF", "LAUNCHELF.CNF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_PS2BBL_INI, size_SYS_CONF_PS2BBL_INI, "SYS-CONF", "PS2BBL.INI", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_PSXBBL_INI, size_SYS_CONF_PSXBBL_INI, "SYS-CONF", "PSXBBL.INI", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_SYSCONF_ICN, size_SYS_CONF_SYSCONF_ICN, "SYS-CONF", "sysconf.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_USBD_IRX, size_SYS_CONF_USBD_IRX, "SYS-CONF", "USBD.IRX", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_CONF_USBHDFSD_IRX, size_SYS_CONF_USBHDFSD_IRX, "SYS-CONF", "USBHDFSD.IRX", mcport);
if (retorno < 0)
{
    return 6;
}

// Writing files for SYS_FMCB-CFG directory...
retorno = write_embed(&SYS_FMCB_CFG_COPY_ICN, size_SYS_FMCB_CFG_COPY_ICN, "SYS_FMCB-CFG", "copy.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_FMCB_CFG_DEL_ICN, size_SYS_FMCB_CFG_DEL_ICN, "SYS_FMCB-CFG", "del.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_FMCB_CFG_FMCB_CFG_ELF, size_SYS_FMCB_CFG_FMCB_CFG_ELF, "SYS_FMCB-CFG", "FMCB-CFG.ELF", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_FMCB_CFG_ICON_SYS, size_SYS_FMCB_CFG_ICON_SYS, "SYS_FMCB-CFG", "icon.sys", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_FMCB_CFG_LIST_ICN, size_SYS_FMCB_CFG_LIST_ICN, "SYS_FMCB-CFG", "list.icn", mcport);
if (retorno < 0)
{
    return 6;
}
retorno = write_embed(&SYS_FMCB_CFG_TITLE_CFG, size_SYS_FMCB_CFG_TITLE_CFG, "SYS_FMCB-CFG", "title.cfg", mcport);
if (retorno < 0)
{
    return 6;
}

	PRINTF("installation finished\n");

	static sceMcTblGetDir mcDirAAA[64] __attribute__((aligned(64)));
	static sceMcStDateTime maximahora; //Maxium Timestamp, for the ones who does not speak Spanish

	maximahora.Resv2 = 0;
	maximahora.Sec = 59;
	maximahora.Min = 59;
	maximahora.Hour = 23;
	maximahora.Day = 31;
	maximahora.Month = 12;
	maximahora.Year = 2099;
	mcDirAAA->_Modify = maximahora;
	mcDirAAA->_Create = maximahora;
	mcSetFileInfo(mcport, 0, "OPENTUNA", mcDirAAA, 0x02);
	mcSync(0, NULL, &ret);

	PRINTF("timestamp changed\n");

	return 0;
}

//--------------------------------------------------------------
// Cleans up resources and prepares the system before exiting or loading another ELF.
// This function is trimmed from FreeMcBoot by SP193.
static void CleanUp(void)
{
	// Finalize PAD system if it was initialized.
	if (pad_inited)
	{
		padPortClose(0, 0); // Close PAD port 0
		padPortClose(1, 0); // Close PAD port 1
		padEnd();           // End PAD library operations
	}

	Reset_IOP(); // Reset the IOP.

	// Re-initialize SIF services and apply patches for loading standard ROM modules.
	SifLoadFileInit();
	sbv_patch_enable_lmb(); // May not be strictly necessary here but often done.
	sbv_patch_disable_prefix_check(); // Should be re-enabled if default behavior is desired.

	// Load standard IOP modules from ROM.
	SifLoadModule("rom0:SIO2MAN", 0, 0);
	SifLoadModule("rom0:CDVDFSV", 0, 0);
	SifLoadModule("rom0:CDVDMAN", 0, 0);
	SifLoadModule("rom0:MCMAN", 0, 0);
	SifLoadModule("rom0:MCSERV", 0, 0);
	SifLoadModule("rom0:PADMAN", 0, 0);

	// Clean up SIF and File I/O services.
	fioExit();
	SifExitIopHeap();
	SifLoadFileExit();
	SifExitRpc();
	SifExitCmd();

	// Flush CPU caches.
	FlushCache(0); // Instruction cache
	FlushCache(2); // Data cache (or 1 for primary data cache, 2 for L1/L2 depending on arch)

	// Clear the screen to black.
	gs_set_fill_color(0, 0, 0); // Set fill color to black
	gs_fill_rect(0, 0, gs_get_max_x(), gs_get_max_y()); // Fill entire screen
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Exits the installer and returns to the PS2 Browser (OSDSYS).
static void PS2_browser(void)
{
	CleanUp(); // Perform all necessary cleanup.
	LoadExecPS2("rom0:OSDSYS", 0, NULL); // Load OSDSYS ELF from ROM0. This function does not return.
}

// Displays an error message screen with a specific message bitmap.
// Args:
//   iz: An integer code corresponding to the error message to display.
//       Different codes map to different MensajeX bitmaps.
void error_message(int iz)
{
	display_bmp(640, 448, error); // Display the generic error background.
	switch (iz) // Select the specific error message overlay.
	{
	case 1: gs_print_bitmap(192, 343, 256, 40, MensajeA); break; // No MC / mcGetInfo error
	case 2: gs_print_bitmap(192, 343, 256, 40, MensajeB); break; // Not a PS2 MC
	case 3: gs_print_bitmap(192, 343, 256, 40, MensajeC); break; // Not enough free space
	case 4: gs_print_bitmap(192, 343, 256, 40, MensajeD); break; // Files already exist
	// Case 5 was for MensajeE, if used, it should be added here. The error codes were refactored.
	// Current error code usage: 1,2,3,4,6,7,8. MensajeE/F might correspond to 6 or other general errors.
	case 5: gs_print_bitmap(192, 343, 256, 40, MensajeE); break; // Example: Could be used for Delete Error (7) or MkDir Error (8)
	case 6: gs_print_bitmap(192, 343, 256, 40, MensajeF); break; // Example: Could be used for general file I/O (6)
	// TODO: Map error codes (iz) more clearly to MensajeX if they don't align with 1-6.
	// For now, this function shows MensajeA-F based on iz=1-6.
	// Error codes passed to 'iz' can be 1,2,3,4,6,7,8.
	// This means iz=5,7,8 currently won't show a specific message here beyond the generic 'error' BMP.
	default:
		// No specific message for this error code, generic error BMP is already shown.
		// Numerical error code printing removed to avoid gs_font_print undefined reference.
		break;
	}

	// Numerical error code display removed due to linker errors with gs_font_print.
	// char err_code_str[32];
	// sprintf(err_code_str, "Error Code: %d", iz);
	// gs_font_print(264, 390, 1, 0x00E0E0E0, err_code_str);
}

// Waits for a specific controller key press (or any key if 'key' is -1).
// Args:
//   key: The PAD_ อะไร (e.g. PAD_CROSS, PAD_START) to wait for.
//        If -1, waits for any key press.
// Returns:
//   The status of the pad when the specified key (or any key) is pressed.
int wait_key(int key)
{
	while (1) // Loop indefinitely until the key is pressed.
	{
		int new_pad = ReadCombinedPadStatus(); // Read combined status of both pads.
		if (key == -1) { // Wait for any key
			if (new_pad != 0) return new_pad;
		} else { // Wait for specific key
			if (new_pad & key)
				return new_pad;
		}
	}
}

// Main function for the UMCS Installer.
// Handles initialization, UI state machine, installation, and cleanup.
// Args:
//   argc: Argument count (not typically used in PS2 homebrew from MC).
//   argv: Argument vector (not typically used).
int main(int argc, char *argv[])
{
	int fdn, icontype;
	unsigned long int ROM_VERSION = 0x170;
	VMode = NTSC; // Default video mode
	int mcport = 0, state; // mcport: selected memory card slot; state: current state of the application
	int key; // Stores controller input

	// Initialize PS2 hardware and basic services (IOP, SIF, FileIO, MC, PAD)
	InitPS2();

	// Reset Graphics Synthesizer (GS) to a known state
	gs_reset();

	// Attempt to read ROM version from rom0:ROMVER.
	// Default to ROM_VERSION = 0x170 and VMode = NTSC if unable to read.
	// Note: ROM_VERSION and VMode are already initialized to these defaults before this block.
	if ((fdn = open("rom0:ROMVER", O_RDONLY)) > 0) // Successfully opened ROMVER
	{
		char romver[5];
		read(fdn, romver, 4); // Read 4 bytes for version, 5th is region
		close(fdn);           // Close the file

		if (romver[4] == 'E') // Check 5th byte for PAL region marker
			VMode = PAL;
		romver[4] = '\0';     // Null-terminate the version string for strtoul
		ROM_VERSION = strtoul(romver, NULL, 16); // Convert hex string to unsigned long
		PRINTF("Main: Successfully read rom0:ROMVER. ROM_VERSION: %lx, VMode: %s\n", ROM_VERSION, VMode == PAL ? "PAL" : "NTSC");
	} else {
		// Failed to open rom0:ROMVER, use default values
		PRINTF("Main: Failed to open rom0:ROMVER (fdn: %d). Using default ROM_VERSION: %lx and VMode: %s\n", fdn, ROM_VERSION, VMode == PAL ? "PAL" : "NTSC");
	}

	// Initialize Graphics Synthesizer based on VMode (PAL or NTSC)
	if (VMode == PAL)
		gs_init(PAL_640_512_32); // Initialize GS for PAL mode
	else
		gs_init(NTSC_640_448_32); // Initialize GS for NTSC mode

	// Initialize PAD input system
	pad_inited = 1;

	// Determine icon type based on ROM version
	icontype = GetIconType(ROM_VERSION);
	int iz = 0; // Variable to store installation result status

	// Set initial state based on ROM compatibility
	if (icontype != UNSUPPORTED)
		state = STATE_MC0; // Compatible ROM, start with MC0 selection
	else
		state = STATE_UNSUPPORTED; // Incompatible ROM

	// Main application loop - finite state machine for UI and actions
	while (1)
	{
		switch (state)
		{
		case STATE_MC0: // State: Displaying options for Memory Card Slot 0
			mcport = 0; // Set current Memory Card port to 0
			display_bmp(640, 448, INST_SLOT_1); // Show screen for MC slot 1 (user perspective)

			key = wait_key(-1); // Wait for any key press

			// Transitions from STATE_MC0
			if ((key & PAD_CROSS) || (key & PAD_CIRCLE)) // X or O pressed
			{
				state = STATE_INSTALL; // Proceed to installation for MC0
				break;
			}
			if ((key & PAD_SELECT) || (key & PAD_L1)) // Select or L1 pressed
			{
				state = STATE_MC1; // Switch to MC1 selection screen
				break;
			}
			// Any other key (typically Start or other unhandled)
			state = STATE_BROWSER; // Exit to PS2 Browser
			break;

		case STATE_MC1: // State: Displaying options for Memory Card Slot 1
			mcport = 1; // Set current Memory Card port to 1
			display_bmp(640, 448, INST_SLOT_2); // Show screen for MC slot 2 (user perspective)

			key = wait_key(-1); // Wait for any key press

			// Transitions from STATE_MC1
			if ((key & PAD_CROSS) || (key & PAD_CIRCLE)) // X or O pressed
			{
				state = STATE_INSTALL; // Proceed to installation for MC1
				break;
			}
			if ((key & PAD_SELECT) || (key & PAD_L1)) // Select or L1 pressed
			{
				state = STATE_MC0; // Switch to MC0 selection screen
				break;
			}
			// Any other key
			state = STATE_BROWSER; // Exit to PS2 Browser
			break;

		case STATE_UNSUPPORTED: // State: Unsupported ROM version detected
			display_bmp(640, 448, NON_COMPATIBLE); // Show non-compatible screen
			key = wait_key(PAD_START); // Wait for Start key press
			state = STATE_BROWSER; // Exit to PS2 Browser
			break;

		case STATE_INSTALL: // State: Performing installation
			display_bmp(640, 448, wait); // Show wait/installation progress screen
			iz = install(mcport, icontype); // Call install function

			// Transitions from STATE_INSTALL
			if (iz) // If install returned an error code (non-zero)
				state = STATE_ERROR; // Go to error screen
			else
				state = STATE_FINISH; // Go to finish/success screen
			break;

		case STATE_FINISH: // State: Installation finished successfully
			display_bmp(640, 448, complete); // Show completion screen
			key = wait_key(PAD_START); // Wait for Start key press
			state = STATE_BROWSER; // Exit to PS2 Browser
			break;

		case STATE_ERROR: // State: Error occurred during installation
			error_message(iz); // Display specific error message based on 'iz' code
			key = wait_key(PAD_START); // Wait for Start key press
			state = STATE_BROWSER; // Exit to PS2 Browser
			break; // Added break, was missing (though execution flows to BROWSER anyway)

		case STATE_BROWSER: // State: Exit to PS2 Browser
			PS2_browser(); // Execute cleanup and load OSDSYS
			break; // Technically unreachable as PS2_browser doesn't return

		default: // Should not happen
			break;
		}
	}

	// This part of the code is unreachable because the main loop (while(1)) never exits,
	// and all program paths eventually lead to PS2_browser() which loads another ELF.
	return 0;
}
