EE_BIN = Installer.elf
EE_BIN_PACKED = OSDMenu-OpenTuna-Installer.ELF
EE_BIN_STRIPPED = stripped.elf
EE_OBJS = main.o gs.o pad.o  gs_asm.o ps2_asm.o dma_asm.o
EE_OBJS += OpenTuna_sys.o OpenTuna_SLIMS.o OpenTuna_FAT-170.o OpenTuna_FAT-110-120-150-160.o \
	APPS_DEL_ICN.o \
	APPS_ICON_SYS.o \
	APPS_LIST_ICN.o \
	APP_ESR_LAUNCHER_COPY_ICN.o \
	APP_ESR_LAUNCHER_DEL_ICN.o \
	APP_ESR_LAUNCHER_ESR_LAUNCHER_ELF.o \
	APP_ESR_LAUNCHER_ICON_SYS.o \
	APP_ESR_LAUNCHER_LIST_ICN.o \
	APP_ESR_LAUNCHER_TITLE_CFG.o \
	APP_NHDDL_COPY_ICN.o \
	APP_NHDDL_DEL_ICN.o \
	APP_NHDDL_ICON_SYS.o \
	APP_NHDDL_LIST_ICN.o \
	APP_NHDDL_NHDDL_ELF.o \
	APP_NHDDL_README_MD.o \
	APP_NHDDL_TITLE_CFG.o \
	APP_OPL_COPY_ICN.o \
	APP_OPL_DEL_ICN.o \
	APP_OPL_ICON_SYS.o \
	APP_OPL_LIST_ICN.o \
	APP_OPL_OPL_ELF.o \
	APP_OPL_TITLE_CFG.o \
	BOOT_BOOT_ELF.o \
	BOOT_BOOT2_ELF.o \
	BOOT_CONFIG_INI.o \
	BOOT_COPY_ICN.o \
	BOOT_DEL_ICN.o \
	BOOT_DKWDRV_ELF.o \
	BOOT_ICON_SYS.o \
	BOOT_LAUNCHER_ELF.o \
	BOOT_LIST_ICN.o \
	BOOT_PATCHER_ELF.o \
	BOOT_TITLE_CFG.o \
	NEUTRINO_DEL_ICN.o \
	NEUTRINO_ICON_SYS.o \
	NEUTRINO_LIST_ICN.o \
	NEUTRINO_NEUTRINO_ELF.o \
	NEUTRINO_VERSION_TXT.o \
	NEUTRINO_CONFIG_BSD_ATA_TOML.o \
	NEUTRINO_CONFIG_BSD_ILINK_TOML.o \
	NEUTRINO_CONFIG_BSD_MMCE_TOML.o \
	NEUTRINO_CONFIG_BSD_MX4SIO_TOML.o \
	NEUTRINO_CONFIG_BSD_UDPBD_HDD_TOML.o \
	NEUTRINO_CONFIG_BSD_UDPBD_TOML.o \
	NEUTRINO_CONFIG_BSD_USB_DEBUG_TOML.o \
	NEUTRINO_CONFIG_BSD_USB_TOML.o \
	NEUTRINO_CONFIG_BSDFS_BD_TOML.o \
	NEUTRINO_CONFIG_BSDFS_EXFAT_TOML.o \
	NEUTRINO_CONFIG_BSDFS_HDL_TOML.o \
	NEUTRINO_CONFIG_EMU_ATA_FILE_TOML.o \
	NEUTRINO_CONFIG_EMU_DVD_ESR_TOML.o \
	NEUTRINO_CONFIG_EMU_DVD_FILE_TOML.o \
	NEUTRINO_CONFIG_EMU_MC_FILE_TOML.o \
	NEUTRINO_CONFIG_I_BDM_TOML.o \
	NEUTRINO_CONFIG_I_DEV9_HIDDEN_TOML.o \
	NEUTRINO_CONFIG_I_DEV9_NS_TOML.o \
	NEUTRINO_CONFIG_PCSX2_HDL_TOML.o \
	NEUTRINO_CONFIG_PCSX2_TOML.o \
	NEUTRINO_CONFIG_RC_UYA_TOML.o \
	NEUTRINO_CONFIG_SYSTEM_TOML.o \
	NEUTRINO_MODULES_ATAD_EMU_IRX.o \
	NEUTRINO_MODULES_ATA_BD_IRX.o \
	NEUTRINO_MODULES_BDFS_IRX.o \
	NEUTRINO_MODULES_BDM_IRX.o \
	NEUTRINO_MODULES_BDMFS_FATFS_IRX.o \
	NEUTRINO_MODULES_CDVDFSV_IRX.o \
	NEUTRINO_MODULES_CDVDMAN_EMU_IRX.o \
	NEUTRINO_MODULES_CDVDMAN_ESR1_IRX.o \
	NEUTRINO_MODULES_CDVDMAN_ESR2_IRX.o \
	NEUTRINO_MODULES_DEV9_HIDDEN_IRX.o \
	NEUTRINO_MODULES_DEV9_NS_IRX.o \
	NEUTRINO_MODULES_EESYNC_IRX.o \
	NEUTRINO_MODULES_EE_CORE_ELF.o \
	NEUTRINO_MODULES_FAKEMOD_IRX.o \
	NEUTRINO_MODULES_FHI_BD_IRX.o \
	NEUTRINO_MODULES_FHI_BD_DEFRAG_IRX.o \
	NEUTRINO_MODULES_FHI_FILE_IRX.o \
	NEUTRINO_MODULES_FILEXIO_IRX.o \
	NEUTRINO_MODULES_GAPFILL_IRX.o \
	NEUTRINO_MODULES_HDLFS_IRX.o \
	NEUTRINO_MODULES_IEEE1394_BD_MINI_IRX.o \
	NEUTRINO_MODULES_ILINKMAN_IRX.o \
	NEUTRINO_MODULES_IMGDRV_IRX.o \
	NEUTRINO_MODULES_IOMANX_IRX.o \
	NEUTRINO_MODULES_ISOFS_IRX.o \
	NEUTRINO_MODULES_MC_EMU_IRX.o \
	NEUTRINO_MODULES_MEMCHECK_IRX.o \
	NEUTRINO_MODULES_MMCEFHI_IRX.o \
	NEUTRINO_MODULES_MMCEMAN_IRX.o \
	NEUTRINO_MODULES_MX4SIO_BD_MINI_IRX.o \
	NEUTRINO_MODULES_PATCH_FREEMEM_IRX.o \
	NEUTRINO_MODULES_PATCH_MEMBO_IRX.o \
	NEUTRINO_MODULES_PATCH_RC_UYA_IRX.o \
	NEUTRINO_MODULES_PS2HDD_BDM_IRX.o \
	NEUTRINO_MODULES_SMAP_UDPBD_IRX.o \
	NEUTRINO_MODULES_SMAP_UDPTTY_IRX.o \
	NEUTRINO_MODULES_UDNL_T300_IRX.o \
	NEUTRINO_MODULES_UDNL_IRX.o \
	NEUTRINO_MODULES_USBD_MINI_IRX.o \
	NEUTRINO_MODULES_USBD_NULL_IRX.o \
	NEUTRINO_MODULES_USBMASS_BD_MINI_IRX.o \
	POPSTARTER_DEL_ICN.o \
	POPSTARTER_ICON_SYS.o \
	POPSTARTER_IPCONFIG_DAT.o \
	POPSTARTER_LIST_ICN.o \
	POPSTARTER_POWEROFF_IRX.o \
	POPSTARTER_PS2DEV9_IRX.o \
	POPSTARTER_PS2IP_IRX.o \
	POPSTARTER_PS2SMAP_IRX.o \
	POPSTARTER_SMBCONFIG_DAT.o \
	POPSTARTER_SMBMAN_IRX.o \
	POPSTARTER_SMSUTILS_IRX.o \
	POPSTARTER_USBD_IRX.o \
	POPSTARTER_USBHDFSD_IRX.o \
	SYS_CONF_COPY_ICN.o \
	SYS_CONF_DEL_ICN.o \
	SYS_CONF_ENDVDPL_IRX.o \
	SYS_CONF_ICON_SYS.o \
	SYS_CONF_IPCONFIG_DAT.o \
	SYS_CONF_LAUNCHELF_CNF.o \
	SYS_CONF_OSDMENU_CNF.o \
	SYS_CONF_PS2BBL_INI.o \
	SYS_CONF_PSXBBL_INI.o \
	SYS_CONF_SYSCONF_ICN.o \
	PADMAN_irx.o SIO2MAN_irx.o MCMAN_irx.o MCSERV_irx.o
EE_SRC = OpenTuna_sys.s OpenTuna_SLIMS.s OpenTuna_FAT-170.s OpenTuna_FAT-110-120-150-160.s \
	APPS_DEL_ICN.s \
	APPS_ICON_SYS.s \
	APPS_LIST_ICN.s \
	APP_ESR_LAUNCHER_COPY_ICN.s \
	APP_ESR_LAUNCHER_DEL_ICN.s \
	APP_ESR_LAUNCHER_ESR_LAUNCHER_ELF.s \
	APP_ESR_LAUNCHER_ICON_SYS.s \
	APP_ESR_LAUNCHER_LIST_ICN.s \
	APP_ESR_LAUNCHER_TITLE_CFG.s \
	APP_NHDDL_COPY_ICN.s \
	APP_NHDDL_DEL_ICN.s \
	APP_NHDDL_ICON_SYS.s \
	APP_NHDDL_LIST_ICN.s \
	APP_NHDDL_NHDDL_ELF.s \
	APP_NHDDL_README_MD.s \
	APP_NHDDL_TITLE_CFG.s \
	APP_OPL_COPY_ICN.s \
	APP_OPL_DEL_ICN.s \
	APP_OPL_ICON_SYS.s \
	APP_OPL_LIST_ICN.s \
	APP_OPL_OPL_ELF.s \
	APP_OPL_TITLE_CFG.s \
	BOOT_BOOT_ELF.s \
	BOOT_BOOT2_ELF.s \
	BOOT_CONFIG_INI.s \
	BOOT_COPY_ICN.s \
	BOOT_DEL_ICN.s \
	BOOT_DKWDRV_ELF.s \
	BOOT_ICON_SYS.s \
	BOOT_LAUNCHER_ELF.s \
	BOOT_LIST_ICN.s \
	BOOT_PATCHER_ELF.s \
	BOOT_TITLE_CFG.s \
	NEUTRINO_DEL_ICN.s \
	NEUTRINO_ICON_SYS.s \
	NEUTRINO_LIST_ICN.s \
	NEUTRINO_NEUTRINO_ELF.s \
	NEUTRINO_VERSION_TXT.s \
	NEUTRINO_CONFIG_BSD_ATA_TOML.s \
	NEUTRINO_CONFIG_BSD_ILINK_TOML.s \
	NEUTRINO_CONFIG_BSD_MMCE_TOML.s \
	NEUTRINO_CONFIG_BSD_MX4SIO_TOML.s \
	NEUTRINO_CONFIG_BSD_UDPBD_HDD_TOML.s \
	NEUTRINO_CONFIG_BSD_UDPBD_TOML.s \
	NEUTRINO_CONFIG_BSD_USB_DEBUG_TOML.s \
	NEUTRINO_CONFIG_BSD_USB_TOML.s \
	NEUTRINO_CONFIG_BSDFS_BD_TOML.s \
	NEUTRINO_CONFIG_BSDFS_EXFAT_TOML.s \
	NEUTRINO_CONFIG_BSDFS_HDL_TOML.s \
	NEUTRINO_CONFIG_EMU_ATA_FILE_TOML.s \
	NEUTRINO_CONFIG_EMU_DVD_ESR_TOML.s \
	NEUTRINO_CONFIG_EMU_DVD_FILE_TOML.s \
	NEUTRINO_CONFIG_EMU_MC_FILE_TOML.s \
	NEUTRINO_CONFIG_I_BDM_TOML.s \
	NEUTRINO_CONFIG_I_DEV9_HIDDEN_TOML.s \
	NEUTRINO_CONFIG_I_DEV9_NS_TOML.s \
	NEUTRINO_CONFIG_PCSX2_HDL_TOML.s \
	NEUTRINO_CONFIG_PCSX2_TOML.s \
	NEUTRINO_CONFIG_RC_UYA_TOML.s \
	NEUTRINO_CONFIG_SYSTEM_TOML.s \
	NEUTRINO_MODULES_ATAD_EMU_IRX.s \
	NEUTRINO_MODULES_ATA_BD_IRX.s \
	NEUTRINO_MODULES_BDFS_IRX.s \
	NEUTRINO_MODULES_BDM_IRX.s \
	NEUTRINO_MODULES_BDMFS_FATFS_IRX.s \
	NEUTRINO_MODULES_CDVDFSV_IRX.s \
	NEUTRINO_MODULES_CDVDMAN_EMU_IRX.s \
	NEUTRINO_MODULES_CDVDMAN_ESR1_IRX.s \
	NEUTRINO_MODULES_CDVDMAN_ESR2_IRX.s \
	NEUTRINO_MODULES_DEV9_HIDDEN_IRX.s \
	NEUTRINO_MODULES_DEV9_NS_IRX.s \
	NEUTRINO_MODULES_EESYNC_IRX.s \
	NEUTRINO_MODULES_EE_CORE_ELF.s \
	NEUTRINO_MODULES_FAKEMOD_IRX.s \
	NEUTRINO_MODULES_FHI_BD_IRX.s \
	NEUTRINO_MODULES_FHI_BD_DEFRAG_IRX.s \
	NEUTRINO_MODULES_FHI_FILE_IRX.s \
	NEUTRINO_MODULES_FILEXIO_IRX.s \
	NEUTRINO_MODULES_GAPFILL_IRX.s \
	NEUTRINO_MODULES_HDLFS_IRX.s \
	NEUTRINO_MODULES_IEEE1394_BD_MINI_IRX.s \
	NEUTRINO_MODULES_ILINKMAN_IRX.s \
	NEUTRINO_MODULES_IMGDRV_IRX.s \
	NEUTRINO_MODULES_IOMANX_IRX.s \
	NEUTRINO_MODULES_ISOFS_IRX.s \
	NEUTRINO_MODULES_MC_EMU_IRX.s \
	NEUTRINO_MODULES_MEMCHECK_IRX.s \
	NEUTRINO_MODULES_MMCEFHI_IRX.s \
	NEUTRINO_MODULES_MMCEMAN_IRX.s \
	NEUTRINO_MODULES_MX4SIO_BD_MINI_IRX.s \
	NEUTRINO_MODULES_PATCH_FREEMEM_IRX.s \
	NEUTRINO_MODULES_PATCH_MEMBO_IRX.s \
	NEUTRINO_MODULES_PATCH_RC_UYA_IRX.s \
	NEUTRINO_MODULES_PS2HDD_BDM_IRX.s \
	NEUTRINO_MODULES_SMAP_UDPBD_IRX.s \
	NEUTRINO_MODULES_SMAP_UDPTTY_IRX.s \
	NEUTRINO_MODULES_UDNL_T300_IRX.s \
	NEUTRINO_MODULES_UDNL_IRX.s \
	NEUTRINO_MODULES_USBD_MINI_IRX.s \
	NEUTRINO_MODULES_USBD_NULL_IRX.s \
	NEUTRINO_MODULES_USBMASS_BD_MINI_IRX.s \
	POPSTARTER_DEL_ICN.s \
	POPSTARTER_ICON_SYS.s \
	POPSTARTER_IPCONFIG_DAT.s \
	POPSTARTER_LIST_ICN.s \
	POPSTARTER_POWEROFF_IRX.s \
	POPSTARTER_PS2DEV9_IRX.s \
	POPSTARTER_PS2IP_IRX.s \
	POPSTARTER_PS2SMAP_IRX.s \
	POPSTARTER_SMBCONFIG_DAT.s \
	POPSTARTER_SMBMAN_IRX.s \
	POPSTARTER_SMSUTILS_IRX.s \
	POPSTARTER_USBD_IRX.s \
	POPSTARTER_USBHDFSD_IRX.s \
	SYS_CONF_COPY_ICN.s \
	SYS_CONF_DEL_ICN.s \
	SYS_CONF_ENDVDPL_IRX.s \
	SYS_CONF_ICON_SYS.s \
	SYS_CONF_IPCONFIG_DAT.s \
	SYS_CONF_LAUNCHELF_CNF.s \
	SYS_CONF_OSDMENU_CNF.s \
	SYS_CONF_PS2BBL_INI.s \
	SYS_CONF_PSXBBL_INI.s \
	SYS_CONF_SYSCONF_ICN.s \
	PADMAN_irx.c SIO2MAN_irx.c MCMAN_irx.c MCSERV_irx.c
EE_LIBS = -ldebug -lcdvd -lpatches -lpadx -lmc

all:
	$(MAKE) $(EE_BIN_PACKED)

APPS_DEL_ICN.s:
	bin2s INSTALL/APPS/DEL.ICN APPS_DEL_ICN.s APPS_DEL_ICN

APPS_ICON_SYS.s:
	bin2s INSTALL/APPS/ICON.SYS APPS_ICON_SYS.s APPS_ICON_SYS

APPS_LIST_ICN.s:
	bin2s INSTALL/APPS/LIST.ICN APPS_LIST_ICN.s APPS_LIST_ICN

APP_ESR_LAUNCHER_COPY_ICN.s:
	bin2s INSTALL/APP_ESR-LAUNCHER/COPY.ICN APP_ESR_LAUNCHER_COPY_ICN.s APP_ESR_LAUNCHER_COPY_ICN

APP_ESR_LAUNCHER_DEL_ICN.s:
	bin2s INSTALL/APP_ESR-LAUNCHER/DEL.ICN APP_ESR_LAUNCHER_DEL_ICN.s APP_ESR_LAUNCHER_DEL_ICN

APP_ESR_LAUNCHER_ESR_LAUNCHER_ELF.s:
	bin2s INSTALL/APP_ESR-LAUNCHER/ESR_LAUNCHER.ELF APP_ESR_LAUNCHER_ESR_LAUNCHER_ELF.s APP_ESR_LAUNCHER_ESR_LAUNCHER_ELF

APP_ESR_LAUNCHER_ICON_SYS.s:
	bin2s INSTALL/APP_ESR-LAUNCHER/ICON.SYS APP_ESR_LAUNCHER_ICON_SYS.s APP_ESR_LAUNCHER_ICON_SYS

APP_ESR_LAUNCHER_LIST_ICN.s:
	bin2s INSTALL/APP_ESR-LAUNCHER/LIST.ICN APP_ESR_LAUNCHER_LIST_ICN.s APP_ESR_LAUNCHER_LIST_ICN

APP_ESR_LAUNCHER_TITLE_CFG.s:
	bin2s INSTALL/APP_ESR-LAUNCHER/TITLE.CFG APP_ESR_LAUNCHER_TITLE_CFG.s APP_ESR_LAUNCHER_TITLE_CFG

APP_NHDDL_COPY_ICN.s:
	bin2s INSTALL/APP_NHDDL/COPY.ICN APP_NHDDL_COPY_ICN.s APP_NHDDL_COPY_ICN

APP_NHDDL_DEL_ICN.s:
	bin2s INSTALL/APP_NHDDL/DEL.ICN APP_NHDDL_DEL_ICN.s APP_NHDDL_DEL_ICN

APP_NHDDL_ICON_SYS.s:
	bin2s INSTALL/APP_NHDDL/ICON.SYS APP_NHDDL_ICON_SYS.s APP_NHDDL_ICON_SYS

APP_NHDDL_LIST_ICN.s:
	bin2s INSTALL/APP_NHDDL/LIST.ICN APP_NHDDL_LIST_ICN.s APP_NHDDL_LIST_ICN

APP_NHDDL_NHDDL_ELF.s:
	bin2s INSTALL/APP_NHDDL/NHDDL.ELF APP_NHDDL_NHDDL_ELF.s APP_NHDDL_NHDDL_ELF

APP_NHDDL_README_MD.s:
	bin2s INSTALL/APP_NHDDL/README.MD APP_NHDDL_README_MD.s APP_NHDDL_README_MD

APP_NHDDL_TITLE_CFG.s:
	bin2s INSTALL/APP_NHDDL/TITLE.CFG APP_NHDDL_TITLE_CFG.s APP_NHDDL_TITLE_CFG

APP_OPL_COPY_ICN.s:
	bin2s INSTALL/APP_OPL/COPY.ICN APP_OPL_COPY_ICN.s APP_OPL_COPY_ICN

APP_OPL_DEL_ICN.s:
	bin2s INSTALL/APP_OPL/DEL.ICN APP_OPL_DEL_ICN.s APP_OPL_DEL_ICN

APP_OPL_ICON_SYS.s:
	bin2s INSTALL/APP_OPL/ICON.SYS APP_OPL_ICON_SYS.s APP_OPL_ICON_SYS

APP_OPL_LIST_ICN.s:
	bin2s INSTALL/APP_OPL/LIST.ICN APP_OPL_LIST_ICN.s APP_OPL_LIST_ICN

APP_OPL_OPL_ELF.s:
	bin2s INSTALL/APP_OPL/OPL.ELF APP_OPL_OPL_ELF.s APP_OPL_OPL_ELF

APP_OPL_TITLE_CFG.s:
	bin2s INSTALL/APP_OPL/TITLE.CFG APP_OPL_TITLE_CFG.s APP_OPL_TITLE_CFG

BOOT_BOOT_ELF.s:
	bin2s INSTALL/BOOT/BOOT.ELF BOOT_BOOT_ELF.s BOOT_BOOT_ELF

BOOT_BOOT2_ELF.s:
	bin2s INSTALL/BOOT/BOOT2.ELF BOOT_BOOT2_ELF.s BOOT_BOOT2_ELF

BOOT_CONFIG_INI.s:
	bin2s INSTALL/BOOT/CONFIG.INI BOOT_CONFIG_INI.s BOOT_CONFIG_INI

BOOT_COPY_ICN.s:
	bin2s INSTALL/BOOT/COPY.ICN BOOT_COPY_ICN.s BOOT_COPY_ICN

BOOT_DEL_ICN.s:
	bin2s INSTALL/BOOT/DEL.ICN BOOT_DEL_ICN.s BOOT_DEL_ICN

BOOT_DKWDRV_ELF.s:
	bin2s INSTALL/BOOT/DKWDRV.ELF BOOT_DKWDRV_ELF.s BOOT_DKWDRV_ELF

BOOT_ICON_SYS.s:
	bin2s INSTALL/BOOT/ICON.SYS BOOT_ICON_SYS.s BOOT_ICON_SYS

BOOT_LAUNCHER_ELF.s:
	bin2s INSTALL/BOOT/LAUNCHER.ELF BOOT_LAUNCHER_ELF.s BOOT_LAUNCHER_ELF

BOOT_LIST_ICN.s:
	bin2s INSTALL/BOOT/LIST.ICN BOOT_LIST_ICN.s BOOT_LIST_ICN

BOOT_PATCHER_ELF.s:
	bin2s INSTALL/BOOT/PATCHER.ELF BOOT_PATCHER_ELF.s BOOT_PATCHER_ELF

BOOT_TITLE_CFG.s:
	bin2s INSTALL/BOOT/TITLE.CFG BOOT_TITLE_CFG.s BOOT_TITLE_CFG

NEUTRINO_DEL_ICN.s:
	bin2s INSTALL/NEUTRINO/DEL.ICN NEUTRINO_DEL_ICN.s NEUTRINO_DEL_ICN

NEUTRINO_ICON_SYS.s:
	bin2s INSTALL/NEUTRINO/ICON.SYS NEUTRINO_ICON_SYS.s NEUTRINO_ICON_SYS

NEUTRINO_LIST_ICN.s:
	bin2s INSTALL/NEUTRINO/LIST.ICN NEUTRINO_LIST_ICN.s NEUTRINO_LIST_ICN

NEUTRINO_NEUTRINO_ELF.s:
	bin2s INSTALL/NEUTRINO/NEUTRINO.ELF NEUTRINO_NEUTRINO_ELF.s NEUTRINO_NEUTRINO_ELF

NEUTRINO_VERSION_TXT.s:
	bin2s INSTALL/NEUTRINO/VERSION.TXT NEUTRINO_VERSION_TXT.s NEUTRINO_VERSION_TXT

NEUTRINO_CONFIG_BSD_ATA_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSD-ATA.TOML NEUTRINO_CONFIG_BSD_ATA_TOML.s NEUTRINO_CONFIG_BSD_ATA_TOML

NEUTRINO_CONFIG_BSD_ILINK_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSD-ILINK.TOML NEUTRINO_CONFIG_BSD_ILINK_TOML.s NEUTRINO_CONFIG_BSD_ILINK_TOML

NEUTRINO_CONFIG_BSD_MMCE_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSD-MMCE.TOML NEUTRINO_CONFIG_BSD_MMCE_TOML.s NEUTRINO_CONFIG_BSD_MMCE_TOML

NEUTRINO_CONFIG_BSD_MX4SIO_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSD-MX4SIO.TOML NEUTRINO_CONFIG_BSD_MX4SIO_TOML.s NEUTRINO_CONFIG_BSD_MX4SIO_TOML

NEUTRINO_CONFIG_BSD_UDPBD_HDD_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSD-UDPBD-HDD.TOML NEUTRINO_CONFIG_BSD_UDPBD_HDD_TOML.s NEUTRINO_CONFIG_BSD_UDPBD_HDD_TOML

NEUTRINO_CONFIG_BSD_UDPBD_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSD-UDPBD.TOML NEUTRINO_CONFIG_BSD_UDPBD_TOML.s NEUTRINO_CONFIG_BSD_UDPBD_TOML

NEUTRINO_CONFIG_BSD_USB_DEBUG_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSD-USB-DEBUG.TOML NEUTRINO_CONFIG_BSD_USB_DEBUG_TOML.s NEUTRINO_CONFIG_BSD_USB_DEBUG_TOML

NEUTRINO_CONFIG_BSD_USB_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSD-USB.TOML NEUTRINO_CONFIG_BSD_USB_TOML.s NEUTRINO_CONFIG_BSD_USB_TOML

NEUTRINO_CONFIG_BSDFS_BD_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSDFS-BD.TOML NEUTRINO_CONFIG_BSDFS_BD_TOML.s NEUTRINO_CONFIG_BSDFS_BD_TOML

NEUTRINO_CONFIG_BSDFS_EXFAT_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSDFS-EXFAT.TOML NEUTRINO_CONFIG_BSDFS_EXFAT_TOML.s NEUTRINO_CONFIG_BSDFS_EXFAT_TOML

NEUTRINO_CONFIG_BSDFS_HDL_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/BSDFS-HDL.TOML NEUTRINO_CONFIG_BSDFS_HDL_TOML.s NEUTRINO_CONFIG_BSDFS_HDL_TOML

NEUTRINO_CONFIG_EMU_ATA_FILE_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/EMU-ATA-FILE.TOML NEUTRINO_CONFIG_EMU_ATA_FILE_TOML.s NEUTRINO_CONFIG_EMU_ATA_FILE_TOML

NEUTRINO_CONFIG_EMU_DVD_ESR_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/EMU-DVD-ESR.TOML NEUTRINO_CONFIG_EMU_DVD_ESR_TOML.s NEUTRINO_CONFIG_EMU_DVD_ESR_TOML

NEUTRINO_CONFIG_EMU_DVD_FILE_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/EMU-DVD-FILE.TOML NEUTRINO_CONFIG_EMU_DVD_FILE_TOML.s NEUTRINO_CONFIG_EMU_DVD_FILE_TOML

NEUTRINO_CONFIG_EMU_MC_FILE_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/EMU-MC-FILE.TOML NEUTRINO_CONFIG_EMU_MC_FILE_TOML.s NEUTRINO_CONFIG_EMU_MC_FILE_TOML

NEUTRINO_CONFIG_I_BDM_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/I_BDM.TOML NEUTRINO_CONFIG_I_BDM_TOML.s NEUTRINO_CONFIG_I_BDM_TOML

NEUTRINO_CONFIG_I_DEV9_HIDDEN_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/I_DEV9_HIDDEN.TOML NEUTRINO_CONFIG_I_DEV9_HIDDEN_TOML.s NEUTRINO_CONFIG_I_DEV9_HIDDEN_TOML

NEUTRINO_CONFIG_I_DEV9_NS_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/I_DEV9_NS.TOML NEUTRINO_CONFIG_I_DEV9_NS_TOML.s NEUTRINO_CONFIG_I_DEV9_NS_TOML

NEUTRINO_CONFIG_PCSX2_HDL_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/PCSX2-HDL.TOML NEUTRINO_CONFIG_PCSX2_HDL_TOML.s NEUTRINO_CONFIG_PCSX2_HDL_TOML

NEUTRINO_CONFIG_PCSX2_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/PCSX2.TOML NEUTRINO_CONFIG_PCSX2_TOML.s NEUTRINO_CONFIG_PCSX2_TOML

NEUTRINO_CONFIG_RC_UYA_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/RC-UYA.TOML NEUTRINO_CONFIG_RC_UYA_TOML.s NEUTRINO_CONFIG_RC_UYA_TOML

NEUTRINO_CONFIG_SYSTEM_TOML.s:
	bin2s INSTALL/NEUTRINO/CONFIG/SYSTEM.TOML NEUTRINO_CONFIG_SYSTEM_TOML.s NEUTRINO_CONFIG_SYSTEM_TOML

NEUTRINO_MODULES_ATAD_EMU_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/ATAD_EMU.IRX NEUTRINO_MODULES_ATAD_EMU_IRX.s NEUTRINO_MODULES_ATAD_EMU_IRX

NEUTRINO_MODULES_ATA_BD_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/ATA_BD.IRX NEUTRINO_MODULES_ATA_BD_IRX.s NEUTRINO_MODULES_ATA_BD_IRX

NEUTRINO_MODULES_BDFS_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/BDFS.IRX NEUTRINO_MODULES_BDFS_IRX.s NEUTRINO_MODULES_BDFS_IRX

NEUTRINO_MODULES_BDM_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/BDM.IRX NEUTRINO_MODULES_BDM_IRX.s NEUTRINO_MODULES_BDM_IRX

NEUTRINO_MODULES_BDMFS_FATFS_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/BDMFS_FATFS.IRX NEUTRINO_MODULES_BDMFS_FATFS_IRX.s NEUTRINO_MODULES_BDMFS_FATFS_IRX

NEUTRINO_MODULES_CDVDFSV_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/CDVDFSV.IRX NEUTRINO_MODULES_CDVDFSV_IRX.s NEUTRINO_MODULES_CDVDFSV_IRX

NEUTRINO_MODULES_CDVDMAN_EMU_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/CDVDMAN_EMU.IRX NEUTRINO_MODULES_CDVDMAN_EMU_IRX.s NEUTRINO_MODULES_CDVDMAN_EMU_IRX

NEUTRINO_MODULES_CDVDMAN_ESR1_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/CDVDMAN_ESR1.IRX NEUTRINO_MODULES_CDVDMAN_ESR1_IRX.s NEUTRINO_MODULES_CDVDMAN_ESR1_IRX

NEUTRINO_MODULES_CDVDMAN_ESR2_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/CDVDMAN_ESR2.IRX NEUTRINO_MODULES_CDVDMAN_ESR2_IRX.s NEUTRINO_MODULES_CDVDMAN_ESR2_IRX

NEUTRINO_MODULES_DEV9_HIDDEN_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/DEV9_HIDDEN.IRX NEUTRINO_MODULES_DEV9_HIDDEN_IRX.s NEUTRINO_MODULES_DEV9_HIDDEN_IRX

NEUTRINO_MODULES_DEV9_NS_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/DEV9_NS.IRX NEUTRINO_MODULES_DEV9_NS_IRX.s NEUTRINO_MODULES_DEV9_NS_IRX

NEUTRINO_MODULES_EESYNC_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/EESYNC.IRX NEUTRINO_MODULES_EESYNC_IRX.s NEUTRINO_MODULES_EESYNC_IRX

NEUTRINO_MODULES_EE_CORE_ELF.s:
	bin2s INSTALL/NEUTRINO/MODULES/EE_CORE.ELF NEUTRINO_MODULES_EE_CORE_ELF.s NEUTRINO_MODULES_EE_CORE_ELF

NEUTRINO_MODULES_FAKEMOD_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/FAKEMOD.IRX NEUTRINO_MODULES_FAKEMOD_IRX.s NEUTRINO_MODULES_FAKEMOD_IRX

NEUTRINO_MODULES_FHI_BD_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/FHI_BD.IRX NEUTRINO_MODULES_FHI_BD_IRX.s NEUTRINO_MODULES_FHI_BD_IRX

NEUTRINO_MODULES_FHI_BD_DEFRAG_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/FHI_BD_DEFRAG.IRX NEUTRINO_MODULES_FHI_BD_DEFRAG_IRX.s NEUTRINO_MODULES_FHI_BD_DEFRAG_IRX

NEUTRINO_MODULES_FHI_FILE_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/FHI_FILE.IRX NEUTRINO_MODULES_FHI_FILE_IRX.s NEUTRINO_MODULES_FHI_FILE_IRX

NEUTRINO_MODULES_FILEXIO_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/FILEXIO.IRX NEUTRINO_MODULES_FILEXIO_IRX.s NEUTRINO_MODULES_FILEXIO_IRX

NEUTRINO_MODULES_GAPFILL_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/GAPFILL.IRX NEUTRINO_MODULES_GAPFILL_IRX.s NEUTRINO_MODULES_GAPFILL_IRX

NEUTRINO_MODULES_HDLFS_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/HDLFS.IRX NEUTRINO_MODULES_HDLFS_IRX.s NEUTRINO_MODULES_HDLFS_IRX

NEUTRINO_MODULES_IEEE1394_BD_MINI_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/IEEE1394_BD_MINI.IRX NEUTRINO_MODULES_IEEE1394_BD_MINI_IRX.s NEUTRINO_MODULES_IEEE1394_BD_MINI_IRX

NEUTRINO_MODULES_ILINKMAN_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/ILINKMAN.IRX NEUTRINO_MODULES_ILINKMAN_IRX.s NEUTRINO_MODULES_ILINKMAN_IRX

NEUTRINO_MODULES_IMGDRV_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/IMGDRV.IRX NEUTRINO_MODULES_IMGDRV_IRX.s NEUTRINO_MODULES_IMGDRV_IRX

NEUTRINO_MODULES_IOMANX_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/IOMANX.IRX NEUTRINO_MODULES_IOMANX_IRX.s NEUTRINO_MODULES_IOMANX_IRX

NEUTRINO_MODULES_ISOFS_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/ISOFS.IRX NEUTRINO_MODULES_ISOFS_IRX.s NEUTRINO_MODULES_ISOFS_IRX

NEUTRINO_MODULES_MC_EMU_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/MC_EMU.IRX NEUTRINO_MODULES_MC_EMU_IRX.s NEUTRINO_MODULES_MC_EMU_IRX

NEUTRINO_MODULES_MEMCHECK_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/MEMCHECK.IRX NEUTRINO_MODULES_MEMCHECK_IRX.s NEUTRINO_MODULES_MEMCHECK_IRX

NEUTRINO_MODULES_MMCEFHI_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/MMCEFHI.IRX NEUTRINO_MODULES_MMCEFHI_IRX.s NEUTRINO_MODULES_MMCEFHI_IRX

NEUTRINO_MODULES_MMCEMAN_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/MMCEMAN.IRX NEUTRINO_MODULES_MMCEMAN_IRX.s NEUTRINO_MODULES_MMCEMAN_IRX

NEUTRINO_MODULES_MX4SIO_BD_MINI_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/MX4SIO_BD_MINI.IRX NEUTRINO_MODULES_MX4SIO_BD_MINI_IRX.s NEUTRINO_MODULES_MX4SIO_BD_MINI_IRX

NEUTRINO_MODULES_PATCH_FREEMEM_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/PATCH_FREEMEM.IRX NEUTRINO_MODULES_PATCH_FREEMEM_IRX.s NEUTRINO_MODULES_PATCH_FREEMEM_IRX

NEUTRINO_MODULES_PATCH_MEMBO_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/PATCH_MEMBO.IRX NEUTRINO_MODULES_PATCH_MEMBO_IRX.s NEUTRINO_MODULES_PATCH_MEMBO_IRX

NEUTRINO_MODULES_PATCH_RC_UYA_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/PATCH_RC_UYA.IRX NEUTRINO_MODULES_PATCH_RC_UYA_IRX.s NEUTRINO_MODULES_PATCH_RC_UYA_IRX

NEUTRINO_MODULES_PS2HDD_BDM_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/PS2HDD-BDM.IRX NEUTRINO_MODULES_PS2HDD_BDM_IRX.s NEUTRINO_MODULES_PS2HDD_BDM_IRX

NEUTRINO_MODULES_SMAP_UDPBD_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/SMAP_UDPBD.IRX NEUTRINO_MODULES_SMAP_UDPBD_IRX.s NEUTRINO_MODULES_SMAP_UDPBD_IRX

NEUTRINO_MODULES_SMAP_UDPTTY_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/SMAP_UDPTTY.IRX NEUTRINO_MODULES_SMAP_UDPTTY_IRX.s NEUTRINO_MODULES_SMAP_UDPTTY_IRX

NEUTRINO_MODULES_UDNL_T300_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/UDNL-T300.IRX NEUTRINO_MODULES_UDNL_T300_IRX.s NEUTRINO_MODULES_UDNL_T300_IRX

NEUTRINO_MODULES_UDNL_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/UDNL.IRX NEUTRINO_MODULES_UDNL_IRX.s NEUTRINO_MODULES_UDNL_IRX

NEUTRINO_MODULES_USBD_MINI_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/USBD_MINI.IRX NEUTRINO_MODULES_USBD_MINI_IRX.s NEUTRINO_MODULES_USBD_MINI_IRX

NEUTRINO_MODULES_USBD_NULL_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/USBD_NULL.IRX NEUTRINO_MODULES_USBD_NULL_IRX.s NEUTRINO_MODULES_USBD_NULL_IRX

NEUTRINO_MODULES_USBMASS_BD_MINI_IRX.s:
	bin2s INSTALL/NEUTRINO/MODULES/USBMASS_BD_MINI.IRX NEUTRINO_MODULES_USBMASS_BD_MINI_IRX.s NEUTRINO_MODULES_USBMASS_BD_MINI_IRX

POPSTARTER_DEL_ICN.s:
	bin2s INSTALL/POPSTARTER/DEL.ICN POPSTARTER_DEL_ICN.s POPSTARTER_DEL_ICN

POPSTARTER_ICON_SYS.s:
	bin2s INSTALL/POPSTARTER/ICON.SYS POPSTARTER_ICON_SYS.s POPSTARTER_ICON_SYS

POPSTARTER_IPCONFIG_DAT.s:
	bin2s INSTALL/POPSTARTER/IPCONFIG.DAT POPSTARTER_IPCONFIG_DAT.s POPSTARTER_IPCONFIG_DAT

POPSTARTER_LIST_ICN.s:
	bin2s INSTALL/POPSTARTER/LIST.ICN POPSTARTER_LIST_ICN.s POPSTARTER_LIST_ICN

POPSTARTER_POWEROFF_IRX.s:
	bin2s INSTALL/POPSTARTER/POWEROFF.IRX POPSTARTER_POWEROFF_IRX.s POPSTARTER_POWEROFF_IRX

POPSTARTER_PS2DEV9_IRX.s:
	bin2s INSTALL/POPSTARTER/PS2DEV9.IRX POPSTARTER_PS2DEV9_IRX.s POPSTARTER_PS2DEV9_IRX

POPSTARTER_PS2IP_IRX.s:
	bin2s INSTALL/POPSTARTER/PS2IP.IRX POPSTARTER_PS2IP_IRX.s POPSTARTER_PS2IP_IRX

POPSTARTER_PS2SMAP_IRX.s:
	bin2s INSTALL/POPSTARTER/PS2SMAP.IRX POPSTARTER_PS2SMAP_IRX.s POPSTARTER_PS2SMAP_IRX

POPSTARTER_SMBCONFIG_DAT.s:
	bin2s INSTALL/POPSTARTER/SMBCONFIG.DAT POPSTARTER_SMBCONFIG_DAT.s POPSTARTER_SMBCONFIG_DAT

POPSTARTER_SMBMAN_IRX.s:
	bin2s INSTALL/POPSTARTER/SMBMAN.IRX POPSTARTER_SMBMAN_IRX.s POPSTARTER_SMBMAN_IRX

POPSTARTER_SMSUTILS_IRX.s:
	bin2s INSTALL/POPSTARTER/SMSUTILS.IRX POPSTARTER_SMSUTILS_IRX.s POPSTARTER_SMSUTILS_IRX

POPSTARTER_USBD_IRX.s:
	bin2s INSTALL/POPSTARTER/USBD.IRX POPSTARTER_USBD_IRX.s POPSTARTER_USBD_IRX

POPSTARTER_USBHDFSD_IRX.s:
	bin2s INSTALL/POPSTARTER/USBHDFSD.IRX POPSTARTER_USBHDFSD_IRX.s POPSTARTER_USBHDFSD_IRX

SYS_CONF_COPY_ICN.s:
	bin2s INSTALL/SYS-CONF/COPY.ICN SYS_CONF_COPY_ICN.s SYS_CONF_COPY_ICN

SYS_CONF_DEL_ICN.s:
	bin2s INSTALL/SYS-CONF/DEL.ICN SYS_CONF_DEL_ICN.s SYS_CONF_DEL_ICN

SYS_CONF_ENDVDPL_IRX.s:
	bin2s INSTALL/SYS-CONF/ENDVDPL.IRX SYS_CONF_ENDVDPL_IRX.s SYS_CONF_ENDVDPL_IRX

SYS_CONF_ICON_SYS.s:
	bin2s INSTALL/SYS-CONF/ICON.SYS SYS_CONF_ICON_SYS.s SYS_CONF_ICON_SYS

SYS_CONF_IPCONFIG_DAT.s:
	bin2s INSTALL/SYS-CONF/IPCONFIG.DAT SYS_CONF_IPCONFIG_DAT.s SYS_CONF_IPCONFIG_DAT

SYS_CONF_LAUNCHELF_CNF.s:
	bin2s INSTALL/SYS-CONF/LAUNCHELF.CNF SYS_CONF_LAUNCHELF_CNF.s SYS_CONF_LAUNCHELF_CNF

SYS_CONF_OSDMENU_CNF.s:
	bin2s INSTALL/SYS-CONF/OSDMENU.CNF SYS_CONF_OSDMENU_CNF.s SYS_CONF_OSDMENU_CNF

SYS_CONF_PS2BBL_INI.s:
	bin2s INSTALL/SYS-CONF/PS2BBL.INI SYS_CONF_PS2BBL_INI.s SYS_CONF_PS2BBL_INI

SYS_CONF_PSXBBL_INI.s:
	bin2s INSTALL/SYS-CONF/PSXBBL.INI SYS_CONF_PSXBBL_INI.s SYS_CONF_PSXBBL_INI

SYS_CONF_SYSCONF_ICN.s:
	bin2s INSTALL/SYS-CONF/SYSCONF.ICN SYS_CONF_SYSCONF_ICN.s SYS_CONF_SYSCONF_ICN

OpenTuna_sys.s:
	bin2s INSTALL/OPENTUNA/icon.sys OpenTuna_sys.s opentuna_sys

OpenTuna_SLIMS.s:
	bin2s INSTALL/OPENTUNA/OpenTuna_Slims.bin OpenTuna_SLIMS.s opentuna_slims

OpenTuna_FAT-110-120-150-160.s:
	bin2s INSTALL/OPENTUNA/OpenTuna_FAT-110-120-150-160.bin OpenTuna_FAT-110-120-150-160.s opentuna_fats

OpenTuna_FAT-170.s:
	bin2s INSTALL/OPENTUNA/OpenTuna_FAT-170.bin OpenTuna_FAT-170.s opentuna_fat170

SIO2MAN_irx.c: $(PS2SDK)/iop/irx/freesio2.irx
	bin2c $(PS2SDK)/iop/irx/freesio2.irx SIO2MAN_irx.c SIO2MAN_irx

MCMAN_irx.c: $(PS2SDK)/iop/irx/mcman.irx
	bin2c $(PS2SDK)/iop/irx/mcman.irx MCMAN_irx.c MCMAN_irx

MCSERV_irx.c: $(PS2SDK)/iop/irx/mcserv.irx
	bin2c $(PS2SDK)/iop/irx/mcserv.irx MCSERV_irx.c MCSERV_irx

PADMAN_irx.c: $(PS2SDK)/iop/irx/freepad.irx
	bin2c $(PS2SDK)/iop/irx/freepad.irx PADMAN_irx.c PADMAN_irx

clean:
	rm -fr $(EE_OBJS) $(EE_BIN_PACKED) $(EE_BIN_STRIPPED) $(EE_BIN) $(EE_SRC)

$(EE_BIN_STRIPPED): $(EE_BIN)
	$(EE_STRIP) -o $@ $<

$(EE_BIN_PACKED): $(EE_BIN_STRIPPED)
	ps2-packer $< $@ > /dev/null

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal
