EE_BIN = Installer.elf
EE_BIN_PACKED = UMCS-OpenTuna.ELF
EE_BIN_STRIPPED = stripped.elf

# Object files from main application code (C and ASM)
EE_OBJS = main.o gs.o pad.o gs_asm.o ps2_asm.o dma_asm.o

# Object files from embedded OpenTuna icon data (INSTALL/OPENTUNA/)
EE_OBJS += OpenTuna_sys.o OpenTuna_SLIMS.o OpenTuna_FAT-170.o OpenTuna_FAT-110-120-150-160.o

# Object files from embedded INSTALL/BOOT/ directory
EE_OBJS += BOOT_BOOT2_ELF.o BOOT_BOOT_ELF.o BOOT_BOOT_ICN.o BOOT_CONFIG_INI.o BOOT_COPY_ICN.o \
	BOOT_DEL_ICN.o BOOT_ESR_ELF.o BOOT_ICON_SYS.o

# Object files from embedded INSTALL/FMCBD-1.953/ directory
EE_OBJS += FMCBD_1_953_COPY_ICN.o FMCBD_1_953_DEL_ICN.o FMCBD_1_953_FMCBD_1_953_ELF.o \
	FMCBD_1_953_FMCB_ICN.o FMCBD_1_953_ICON_SYS.o

# Object files from embedded INSTALL/FMCBD-1.966/ directory
EE_OBJS += FMCBD_1_966_COPY_ICN.o FMCBD_1_966_DEL_ICN.o FMCBD_1_966_FMCBD_1_966_ELF.o \
	FMCBD_1_966_FMCB_ICN.o FMCBD_1_966_ICON_SYS.o

# Object files from embedded INSTALL/OSDMENU/ directory
EE_OBJS += OSDMENU_COPY_ICN.o OSDMENU_DEL_ICN.o OSDMENU_ICON_SYS.o OSDMENU_LAUNCHER_ELF.o \
	OSDMENU_LIST_ICN.o OSDMENU_OSDMENU_CNF.o OSDMENU_OSDMENU_ELF.o OSDMENU_PATCHER_ELF.o

# Object files from embedded INSTALL/POPSTARTER/ directory
EE_OBJS += POPSTARTER_DEL_ICN.o POPSTARTER_ICON_SYS.o POPSTARTER_IPCONFIG_DAT.o \
	POPSTARTER_LIST_ICN.o POPSTARTER_POWEROFF_IRX.o POPSTARTER_PS2DEV9_IRX.o \
	POPSTARTER_PS2IP_IRX.o POPSTARTER_PS2SMAP_IRX.o POPSTARTER_SMBCONFIG_DAT.o \
	POPSTARTER_SMBMAN_IRX.o POPSTARTER_SMSUTILS_IRX.o POPSTARTER_USBD_IRX.o \
	POPSTARTER_USBHDFSD_IRX.o

# Object files from embedded INSTALL/POWEROFF/ directory
EE_OBJS += POWEROFF_DEL_ICN.o POWEROFF_ICON_SYS.o POWEROFF_LIST_ICN.o POWEROFF_POWEROFF_ELF.o

# Object files from embedded INSTALL/PS1_DKWDRV/ directory
EE_OBJS += PS1_DKWDRV_COPY_ICN.o PS1_DKWDRV_DEL_ICN.o PS1_DKWDRV_DKWDRV_ELF.o \
	PS1_DKWDRV_ICON_SYS.o PS1_DKWDRV_LIST_ICN.o PS1_DKWDRV_TITLE_CFG.o

# Object files from embedded INSTALL/SYS-CONF/ directory
EE_OBJS += SYS_CONF_COPY_ICN.o SYS_CONF_DEL_ICN.o SYS_CONF_ENDVDPL_IRX.o SYS_CONF_FREEMCB_CNF.o \
	SYS_CONF_ICON_SYS.o SYS_CONF_IPCONFIG_DAT.o SYS_CONF_LAUNCHELF_CNF.o SYS_CONF_PS2BBL_INI.o \
	SYS_CONF_PSXBBL_INI.o SYS_CONF_SYSCONF_ICN.o SYS_CONF_USBD_IRX.o SYS_CONF_USBHDFSD_IRX.o

# Object files from embedded INSTALL/SYS_FMCB-CFG/ directory
EE_OBJS += SYS_FMCB_CFG_COPY_ICN.o SYS_FMCB_CFG_DEL_ICN.o SYS_FMCB_CFG_FMCB_CFG_ELF.o \
	SYS_FMCB_CFG_ICON_SYS.o SYS_FMCB_CFG_LIST_ICN.o SYS_FMCB_CFG_TITLE_CFG.o

# Object files from embedded IOP IRX modules (converted to C by bin2c)
EE_OBJS += PADMAN_irx.o SIO2MAN_irx.o MCMAN_irx.o MCSERV_irx.o


# Generated source files (from bin2s and bin2c)
# Sources from embedded OpenTuna icon data (INSTALL/OPENTUNA/)
EE_SRC = OpenTuna_sys.s OpenTuna_SLIMS.s OpenTuna_FAT-170.s OpenTuna_FAT-110-120-150-160.s

# Sources from embedded INSTALL/BOOT/ directory
EE_SRC += BOOT_BOOT2_ELF.s BOOT_BOOT_ELF.s BOOT_BOOT_ICN.s BOOT_CONFIG_INI.s BOOT_COPY_ICN.s \
	BOOT_DEL_ICN.s BOOT_ESR_ELF.s BOOT_ICON_SYS.s

# Sources from embedded INSTALL/FMCBD-1.953/ directory
EE_SRC += FMCBD_1_953_COPY_ICN.s FMCBD_1_953_DEL_ICN.s FMCBD_1_953_FMCBD_1_953_ELF.s \
	FMCBD_1_953_FMCB_ICN.s FMCBD_1_953_ICON_SYS.s

# Sources from embedded INSTALL/FMCBD-1.966/ directory
EE_SRC += FMCBD_1_966_COPY_ICN.s FMCBD_1_966_DEL_ICN.s FMCBD_1_966_FMCBD_1_966_ELF.s \
	FMCBD_1_966_FMCB_ICN.s FMCBD_1_966_ICON_SYS.s

# Sources from embedded INSTALL/OSDMENU/ directory
EE_SRC += OSDMENU_COPY_ICN.s OSDMENU_DEL_ICN.s OSDMENU_ICON_SYS.s OSDMENU_LAUNCHER_ELF.s \
	OSDMENU_LIST_ICN.s OSDMENU_OSDMENU_CNF.s OSDMENU_OSDMENU_ELF.s OSDMENU_PATCHER_ELF.s

# Sources from embedded INSTALL/POPSTARTER/ directory
EE_SRC += POPSTARTER_DEL_ICN.s POPSTARTER_ICON_SYS.s POPSTARTER_IPCONFIG_DAT.s \
	POPSTARTER_LIST_ICN.s POPSTARTER_POWEROFF_IRX.s POPSTARTER_PS2DEV9_IRX.s \
	POPSTARTER_PS2IP_IRX.s POPSTARTER_PS2SMAP_IRX.s POPSTARTER_SMBCONFIG_DAT.s \
	POPSTARTER_SMBMAN_IRX.s POPSTARTER_SMSUTILS_IRX.s POPSTARTER_USBD_IRX.s \
	POPSTARTER_USBHDFSD_IRX.s

# Sources from embedded INSTALL/POWEROFF/ directory
EE_SRC += POWEROFF_DEL_ICN.s POWEROFF_ICON_SYS.s POWEROFF_LIST_ICN.s POWEROFF_POWEROFF_ELF.s

# Sources from embedded INSTALL/PS1_DKWDRV/ directory
EE_SRC += PS1_DKWDRV_COPY_ICN.s PS1_DKWDRV_DEL_ICN.s PS1_DKWDRV_DKWDRV_ELF.s \
	PS1_DKWDRV_ICON_SYS.s PS1_DKWDRV_LIST_ICN.s PS1_DKWDRV_TITLE_CFG.s

# Sources from embedded INSTALL/SYS-CONF/ directory
EE_SRC += SYS_CONF_COPY_ICN.s SYS_CONF_DEL_ICN.s SYS_CONF_ENDVDPL_IRX.s SYS_CONF_FREEMCB_CNF.s \
	SYS_CONF_ICON_SYS.s SYS_CONF_IPCONFIG_DAT.s SYS_CONF_LAUNCHELF_CNF.s SYS_CONF_PS2BBL_INI.s \
	SYS_CONF_PSXBBL_INI.s SYS_CONF_SYSCONF_ICN.s SYS_CONF_USBD_IRX.s SYS_CONF_USBHDFSD_IRX.s

# Sources from embedded INSTALL/SYS_FMCB-CFG/ directory
EE_SRC += SYS_FMCB_CFG_COPY_ICN.s SYS_FMCB_CFG_DEL_ICN.s SYS_FMCB_CFG_FMCB_CFG_ELF.s \
	SYS_FMCB_CFG_ICON_SYS.s SYS_FMCB_CFG_LIST_ICN.s SYS_FMCB_CFG_TITLE_CFG.s

# Sources from embedded IOP IRX modules (converted to C by bin2c)
EE_SRC += PADMAN_irx.c SIO2MAN_irx.c MCMAN_irx.c MCSERV_irx.c

EE_LIBS = -ldebug -lcdvd -lpatches -lpadx -lmc

all:
	$(MAKE) $(EE_BIN_PACKED)

# Rules to convert binary asset files to embeddable assembly objects
BOOT_BOOT_ELF.s: INSTALL/BOOT/BOOT.ELF
	bin2s INSTALL/BOOT/BOOT.ELF BOOT_BOOT_ELF.s BOOT_BOOT_ELF

BOOT_BOOT_ICN.s: INSTALL/BOOT/BOOT.ICN
	bin2s INSTALL/BOOT/BOOT.ICN BOOT_BOOT_ICN.s BOOT_BOOT_ICN

BOOT_BOOT2_ELF.s: INSTALL/BOOT/BOOT2.ELF
	bin2s INSTALL/BOOT/BOOT2.ELF BOOT_BOOT2_ELF.s BOOT_BOOT2_ELF

BOOT_CONFIG_INI.s: INSTALL/BOOT/CONFIG.INI
	bin2s INSTALL/BOOT/CONFIG.INI BOOT_CONFIG_INI.s BOOT_CONFIG_INI

BOOT_COPY_ICN.s: INSTALL/BOOT/COPY.ICN
	bin2s INSTALL/BOOT/COPY.ICN BOOT_COPY_ICN.s BOOT_COPY_ICN

BOOT_DEL_ICN.s: INSTALL/BOOT/DEL.ICN
	bin2s INSTALL/BOOT/DEL.ICN BOOT_DEL_ICN.s BOOT_DEL_ICN

BOOT_ESR_ELF.s: INSTALL/BOOT/ESR.ELF
	bin2s INSTALL/BOOT/ESR.ELF BOOT_ESR_ELF.s BOOT_ESR_ELF

BOOT_ICON_SYS.s: INSTALL/BOOT/ICON.SYS
	bin2s INSTALL/BOOT/ICON.SYS BOOT_ICON_SYS.s BOOT_ICON_SYS

FMCBD_1_953_COPY_ICN.s: INSTALL/FMCBD-1.953/COPY.ICN
	bin2s INSTALL/FMCBD-1.953/COPY.ICN FMCBD_1_953_COPY_ICN.s FMCBD_1_953_COPY_ICN

FMCBD_1_953_DEL_ICN.s: INSTALL/FMCBD-1.953/DEL.ICN
	bin2s INSTALL/FMCBD-1.953/DEL.ICN FMCBD_1_953_DEL_ICN.s FMCBD_1_953_DEL_ICN

FMCBD_1_953_FMCB_ICN.s: INSTALL/FMCBD-1.953/FMCB.ICN
	bin2s INSTALL/FMCBD-1.953/FMCB.ICN FMCBD_1_953_FMCB_ICN.s FMCBD_1_953_FMCB_ICN

FMCBD_1_953_FMCBD_1_953_ELF.s: INSTALL/FMCBD-1.953/FMCBD-1.953.ELF
	bin2s INSTALL/FMCBD-1.953/FMCBD-1.953.ELF FMCBD_1_953_FMCBD_1_953_ELF.s FMCBD_1_953_FMCBD_1_953_ELF

FMCBD_1_953_ICON_SYS.s: INSTALL/FMCBD-1.953/ICON.SYS
	bin2s INSTALL/FMCBD-1.953/ICON.SYS FMCBD_1_953_ICON_SYS.s FMCBD_1_953_ICON_SYS

FMCBD_1_966_COPY_ICN.s: INSTALL/FMCBD-1.966/COPY.ICN
	bin2s INSTALL/FMCBD-1.966/COPY.ICN FMCBD_1_966_COPY_ICN.s FMCBD_1_966_COPY_ICN

FMCBD_1_966_DEL_ICN.s: INSTALL/FMCBD-1.966/DEL.ICN
	bin2s INSTALL/FMCBD-1.966/DEL.ICN FMCBD_1_966_DEL_ICN.s FMCBD_1_966_DEL_ICN

FMCBD_1_966_FMCB_ICN.s: INSTALL/FMCBD-1.966/FMCB.ICN
	bin2s INSTALL/FMCBD-1.966/FMCB.ICN FMCBD_1_966_FMCB_ICN.s FMCBD_1_966_FMCB_ICN

FMCBD_1_966_FMCBD_1_966_ELF.s: INSTALL/FMCBD-1.966/FMCBD-1.966.ELF
	bin2s INSTALL/FMCBD-1.966/FMCBD-1.966.ELF FMCBD_1_966_FMCBD_1_966_ELF.s FMCBD_1_966_FMCBD_1_966_ELF

FMCBD_1_966_ICON_SYS.s: INSTALL/FMCBD-1.966/ICON.SYS
	bin2s INSTALL/FMCBD-1.966/ICON.SYS FMCBD_1_966_ICON_SYS.s FMCBD_1_966_ICON_SYS

OSDMENU_COPY_ICN.s: INSTALL/OSDMENU/COPY.ICN
	bin2s INSTALL/OSDMENU/COPY.ICN OSDMENU_COPY_ICN.s OSDMENU_COPY_ICN

OSDMENU_DEL_ICN.s: INSTALL/OSDMENU/DEL.ICN
	bin2s INSTALL/OSDMENU/DEL.ICN OSDMENU_DEL_ICN.s OSDMENU_DEL_ICN

OSDMENU_ICON_SYS.s: INSTALL/OSDMENU/ICON.SYS
	bin2s INSTALL/OSDMENU/ICON.SYS OSDMENU_ICON_SYS.s OSDMENU_ICON_SYS

OSDMENU_LAUNCHER_ELF.s: INSTALL/OSDMENU/LAUNCHER.ELF
	bin2s INSTALL/OSDMENU/LAUNCHER.ELF OSDMENU_LAUNCHER_ELF.s OSDMENU_LAUNCHER_ELF

OSDMENU_LIST_ICN.s: INSTALL/OSDMENU/LIST.ICN
	bin2s INSTALL/OSDMENU/LIST.ICN OSDMENU_LIST_ICN.s OSDMENU_LIST_ICN

OSDMENU_OSDMENU_CNF.s: INSTALL/OSDMENU/OSDMENU.CNF
	bin2s INSTALL/OSDMENU/OSDMENU.CNF OSDMENU_OSDMENU_CNF.s OSDMENU_OSDMENU_CNF

OSDMENU_OSDMENU_ELF.s: INSTALL/OSDMENU/OSDMENU.ELF
	bin2s INSTALL/OSDMENU/OSDMENU.ELF OSDMENU_OSDMENU_ELF.s OSDMENU_OSDMENU_ELF

OSDMENU_PATCHER_ELF.s: INSTALL/OSDMENU/PATCHER.ELF
	bin2s INSTALL/OSDMENU/PATCHER.ELF OSDMENU_PATCHER_ELF.s OSDMENU_PATCHER_ELF

POPSTARTER_DEL_ICN.s: INSTALL/POPSTARTER/DEL.ICN
	bin2s INSTALL/POPSTARTER/DEL.ICN POPSTARTER_DEL_ICN.s POPSTARTER_DEL_ICN

POPSTARTER_ICON_SYS.s: INSTALL/POPSTARTER/ICON.SYS
	bin2s INSTALL/POPSTARTER/ICON.SYS POPSTARTER_ICON_SYS.s POPSTARTER_ICON_SYS

POPSTARTER_IPCONFIG_DAT.s: INSTALL/POPSTARTER/IPCONFIG.DAT
	bin2s INSTALL/POPSTARTER/IPCONFIG.DAT POPSTARTER_IPCONFIG_DAT.s POPSTARTER_IPCONFIG_DAT

POPSTARTER_LIST_ICN.s: INSTALL/POPSTARTER/LIST.ICN
	bin2s INSTALL/POPSTARTER/LIST.ICN POPSTARTER_LIST_ICN.s POPSTARTER_LIST_ICN

POPSTARTER_POWEROFF_IRX.s: INSTALL/POPSTARTER/POWEROFF.IRX
	bin2s INSTALL/POPSTARTER/POWEROFF.IRX POPSTARTER_POWEROFF_IRX.s POPSTARTER_POWEROFF_IRX

POPSTARTER_PS2DEV9_IRX.s: INSTALL/POPSTARTER/PS2DEV9.IRX
	bin2s INSTALL/POPSTARTER/PS2DEV9.IRX POPSTARTER_PS2DEV9_IRX.s POPSTARTER_PS2DEV9_IRX

POPSTARTER_PS2IP_IRX.s: INSTALL/POPSTARTER/PS2IP.IRX
	bin2s INSTALL/POPSTARTER/PS2IP.IRX POPSTARTER_PS2IP_IRX.s POPSTARTER_PS2IP_IRX

POPSTARTER_PS2SMAP_IRX.s: INSTALL/POPSTARTER/PS2SMAP.IRX
	bin2s INSTALL/POPSTARTER/PS2SMAP.IRX POPSTARTER_PS2SMAP_IRX.s POPSTARTER_PS2SMAP_IRX

POPSTARTER_SMBCONFIG_DAT.s: INSTALL/POPSTARTER/SMBCONFIG.DAT
	bin2s INSTALL/POPSTARTER/SMBCONFIG.DAT POPSTARTER_SMBCONFIG_DAT.s POPSTARTER_SMBCONFIG_DAT

POPSTARTER_SMBMAN_IRX.s: INSTALL/POPSTARTER/SMBMAN.IRX
	bin2s INSTALL/POPSTARTER/SMBMAN.IRX POPSTARTER_SMBMAN_IRX.s POPSTARTER_SMBMAN_IRX

POPSTARTER_SMSUTILS_IRX.s: INSTALL/POPSTARTER/SMSUTILS.IRX
	bin2s INSTALL/POPSTARTER/SMSUTILS.IRX POPSTARTER_SMSUTILS_IRX.s POPSTARTER_SMSUTILS_IRX

POPSTARTER_USBD_IRX.s: INSTALL/POPSTARTER/USBD.IRX
	bin2s INSTALL/POPSTARTER/USBD.IRX POPSTARTER_USBD_IRX.s POPSTARTER_USBD_IRX

POPSTARTER_USBHDFSD_IRX.s: INSTALL/POPSTARTER/USBHDFSD.IRX
	bin2s INSTALL/POPSTARTER/USBHDFSD.IRX POPSTARTER_USBHDFSD_IRX.s POPSTARTER_USBHDFSD_IRX

POWEROFF_DEL_ICN.s: INSTALL/POWEROFF/DEL.ICN
	bin2s INSTALL/POWEROFF/DEL.ICN POWEROFF_DEL_ICN.s POWEROFF_DEL_ICN

POWEROFF_ICON_SYS.s: INSTALL/POWEROFF/ICON.SYS
	bin2s INSTALL/POWEROFF/ICON.SYS POWEROFF_ICON_SYS.s POWEROFF_ICON_SYS

POWEROFF_LIST_ICN.s: INSTALL/POWEROFF/LIST.ICN
	bin2s INSTALL/POWEROFF/LIST.ICN POWEROFF_LIST_ICN.s POWEROFF_LIST_ICN

POWEROFF_POWEROFF_ELF.s: INSTALL/POWEROFF/POWEROFF.ELF
	bin2s INSTALL/POWEROFF/POWEROFF.ELF POWEROFF_POWEROFF_ELF.s POWEROFF_POWEROFF_ELF

PS1_DKWDRV_COPY_ICN.s: INSTALL/PS1_DKWDRV/COPY.ICN
	bin2s INSTALL/PS1_DKWDRV/COPY.ICN PS1_DKWDRV_COPY_ICN.s PS1_DKWDRV_COPY_ICN

PS1_DKWDRV_DEL_ICN.s: INSTALL/PS1_DKWDRV/DEL.ICN
	bin2s INSTALL/PS1_DKWDRV/DEL.ICN PS1_DKWDRV_DEL_ICN.s PS1_DKWDRV_DEL_ICN

PS1_DKWDRV_DKWDRV_ELF.s: INSTALL/PS1_DKWDRV/DKWDRV.ELF
	bin2s INSTALL/PS1_DKWDRV/DKWDRV.ELF PS1_DKWDRV_DKWDRV_ELF.s PS1_DKWDRV_DKWDRV_ELF

PS1_DKWDRV_ICON_SYS.s: INSTALL/PS1_DKWDRV/ICON.SYS
	bin2s INSTALL/PS1_DKWDRV/ICON.SYS PS1_DKWDRV_ICON_SYS.s PS1_DKWDRV_ICON_SYS

PS1_DKWDRV_LIST_ICN.s: INSTALL/PS1_DKWDRV/LIST.ICN
	bin2s INSTALL/PS1_DKWDRV/LIST.ICN PS1_DKWDRV_LIST_ICN.s PS1_DKWDRV_LIST_ICN

PS1_DKWDRV_TITLE_CFG.s: INSTALL/PS1_DKWDRV/TITLE.CFG
	bin2s INSTALL/PS1_DKWDRV/TITLE.CFG PS1_DKWDRV_TITLE_CFG.s PS1_DKWDRV_TITLE_CFG

SYS_CONF_COPY_ICN.s: INSTALL/SYS-CONF/COPY.ICN
	bin2s INSTALL/SYS-CONF/COPY.ICN SYS_CONF_COPY_ICN.s SYS_CONF_COPY_ICN

SYS_CONF_DEL_ICN.s: INSTALL/SYS-CONF/DEL.ICN
	bin2s INSTALL/SYS-CONF/DEL.ICN SYS_CONF_DEL_ICN.s SYS_CONF_DEL_ICN

SYS_CONF_ENDVDPL_IRX.s: INSTALL/SYS-CONF/ENDVDPL.IRX
	bin2s INSTALL/SYS-CONF/ENDVDPL.IRX SYS_CONF_ENDVDPL_IRX.s SYS_CONF_ENDVDPL_IRX

SYS_CONF_FREEMCB_CNF.s: INSTALL/SYS-CONF/FREEMCB.CNF
	bin2s INSTALL/SYS-CONF/FREEMCB.CNF SYS_CONF_FREEMCB_CNF.s SYS_CONF_FREEMCB_CNF

SYS_CONF_ICON_SYS.s: INSTALL/SYS-CONF/ICON.SYS
	bin2s INSTALL/SYS-CONF/ICON.SYS SYS_CONF_ICON_SYS.s SYS_CONF_ICON_SYS

SYS_CONF_IPCONFIG_DAT.s: INSTALL/SYS-CONF/IPCONFIG.DAT
	bin2s INSTALL/SYS-CONF/IPCONFIG.DAT SYS_CONF_IPCONFIG_DAT.s SYS_CONF_IPCONFIG_DAT

SYS_CONF_LAUNCHELF_CNF.s: INSTALL/SYS-CONF/LAUNCHELF.CNF
	bin2s INSTALL/SYS-CONF/LAUNCHELF.CNF SYS_CONF_LAUNCHELF_CNF.s SYS_CONF_LAUNCHELF_CNF

SYS_CONF_PS2BBL_INI.s: INSTALL/SYS-CONF/PS2BBL.INI
	bin2s INSTALL/SYS-CONF/PS2BBL.INI SYS_CONF_PS2BBL_INI.s SYS_CONF_PS2BBL_INI

SYS_CONF_PSXBBL_INI.s: INSTALL/SYS-CONF/PSXBBL.INI
	bin2s INSTALL/SYS-CONF/PSXBBL.INI SYS_CONF_PSXBBL_INI.s SYS_CONF_PSXBBL_INI

SYS_CONF_SYSCONF_ICN.s: INSTALL/SYS-CONF/SYSCONF.ICN
	bin2s INSTALL/SYS-CONF/SYSCONF.ICN SYS_CONF_SYSCONF_ICN.s SYS_CONF_SYSCONF_ICN

SYS_CONF_USBD_IRX.s: INSTALL/SYS-CONF/USBD.IRX
	bin2s INSTALL/SYS-CONF/USBD.IRX SYS_CONF_USBD_IRX.s SYS_CONF_USBD_IRX

SYS_CONF_USBHDFSD_IRX.s: INSTALL/SYS-CONF/USBHDFSD.IRX
	bin2s INSTALL/SYS-CONF/USBHDFSD.IRX SYS_CONF_USBHDFSD_IRX.s SYS_CONF_USBHDFSD_IRX

SYS_FMCB_CFG_COPY_ICN.s: INSTALL/SYS_FMCB-CFG/COPY.ICN
	bin2s INSTALL/SYS_FMCB-CFG/COPY.ICN SYS_FMCB_CFG_COPY_ICN.s SYS_FMCB_CFG_COPY_ICN

SYS_FMCB_CFG_DEL_ICN.s: INSTALL/SYS_FMCB-CFG/DEL.ICN
	bin2s INSTALL/SYS_FMCB-CFG/DEL.ICN SYS_FMCB_CFG_DEL_ICN.s SYS_FMCB_CFG_DEL_ICN

SYS_FMCB_CFG_FMCB_CFG_ELF.s: INSTALL/SYS_FMCB-CFG/FMCB-CFG.ELF
	bin2s INSTALL/SYS_FMCB-CFG/FMCB-CFG.ELF SYS_FMCB_CFG_FMCB_CFG_ELF.s SYS_FMCB_CFG_FMCB_CFG_ELF

SYS_FMCB_CFG_ICON_SYS.s: INSTALL/SYS_FMCB-CFG/ICON.SYS
	bin2s INSTALL/SYS_FMCB-CFG/ICON.SYS SYS_FMCB_CFG_ICON_SYS.s SYS_FMCB_CFG_ICON_SYS

SYS_FMCB_CFG_LIST_ICN.s: INSTALL/SYS_FMCB-CFG/LIST.ICN
	bin2s INSTALL/SYS_FMCB-CFG/LIST.ICN SYS_FMCB_CFG_LIST_ICN.s SYS_FMCB_CFG_LIST_ICN

SYS_FMCB_CFG_TITLE_CFG.s: INSTALL/SYS_FMCB-CFG/TITLE.CFG
	bin2s INSTALL/SYS_FMCB-CFG/TITLE.CFG SYS_FMCB_CFG_TITLE_CFG.s SYS_FMCB_CFG_TITLE_CFG

OpenTuna_sys.s: INSTALL/OPENTUNA/icon.sys
	bin2s INSTALL/OPENTUNA/icon.sys OpenTuna_sys.s opentuna_sys

OpenTuna_SLIMS.s: INSTALL/OPENTUNA/OpenTuna_Slims.bin
	bin2s INSTALL/OPENTUNA/OpenTuna_Slims.bin OpenTuna_SLIMS.s opentuna_slims

OpenTuna_FAT-110-120-150-160.s: INSTALL/OPENTUNA/OpenTuna_FAT-110-120-150-160.bin
	bin2s INSTALL/OPENTUNA/OpenTuna_FAT-110-120-150-160.bin OpenTuna_FAT-110-120-150-160.s opentuna_fats

OpenTuna_FAT-170.s: INSTALL/OPENTUNA/OpenTuna_FAT-170.bin
	bin2s INSTALL/OPENTUNA/OpenTuna_FAT-170.bin OpenTuna_FAT-170.s opentuna_fat170

# Rules to convert IRX binary files to embeddable C arrays
SIO2MAN_irx.c: $(PS2SDK)/iop/irx/freesio2.irx
	bin2c $(PS2SDK)/iop/irx/freesio2.irx SIO2MAN_irx.c SIO2MAN_irx

MCMAN_irx.c: $(PS2SDK)/iop/irx/mcman.irx
	bin2c $(PS2SDK)/iop/irx/mcman.irx MCMAN_irx.c MCMAN_irx

MCSERV_irx.c: $(PS2SDK)/iop/irx/mcserv.irx
	bin2c $(PS2SDK)/iop/irx/mcserv.irx MCSERV_irx.c MCSERV_irx

PADMAN_irx.c: $(PS2SDK)/iop/irx/freepad.irx
	bin2c $(PS2SDK)/iop/irx/freepad.irx PADMAN_irx.c PADMAN_irx

clean:
	rm -fr $(EE_OBJS) $(EE_BIN_PACKED) $(EE_BIN_STRIPPED) $(EE_BIN) $(EE_SRC)

$(EE_BIN_STRIPPED): $(EE_BIN)
	$(EE_STRIP) -o $@ $<

$(EE_BIN_PACKED): $(EE_BIN_STRIPPED)
	ps2-packer $< $@ > /dev/null

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal
